using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Uniandes.Utilidades
{
    public class TreeField
    {

        public string id { get; set; }  //   : "string" // will be autogenerated if omitted
        public string parent { get; set; } //alternative

        public string text { get; set; }  //      : "string" // node text
        public string icon { get; set; }  //     : "string" // string for custom
        public Estados state { get; set; }
       public string type {get;set;}
        //public List<TreeField> children { get; set; }  //   : []  // array of strings or objects
        public Li_attr li_attr { get; set; }  // attributes for the generated LI node
        //a_attr      : {}
    }

    public class Estados
    {
        public Boolean opened { get; set; } // : boolean  // is the node open
        public Boolean disabled { get; set; } //: boolean  // is the node disabled
        public Boolean selected { get; set; } //: boolean  // is the node selected

    }

    public class Li_attr {

        public string rel { get; set; }
    
    }
}
