#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centralizador.DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="centralizador")]
	public partial class CentralizadorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb001_PAIS(tb001_PAIS instance);
    partial void Updatetb001_PAIS(tb001_PAIS instance);
    partial void Deletetb001_PAIS(tb001_PAIS instance);
    partial void Inserttb009_ENTIDADES(tb009_ENTIDADES instance);
    partial void Updatetb009_ENTIDADES(tb009_ENTIDADES instance);
    partial void Deletetb009_ENTIDADES(tb009_ENTIDADES instance);
    partial void Inserttb002_DEPARTAMENTO(tb002_DEPARTAMENTO instance);
    partial void Updatetb002_DEPARTAMENTO(tb002_DEPARTAMENTO instance);
    partial void Deletetb002_DEPARTAMENTO(tb002_DEPARTAMENTO instance);
    partial void Inserttb003_MUNICIPIO(tb003_MUNICIPIO instance);
    partial void Updatetb003_MUNICIPIO(tb003_MUNICIPIO instance);
    partial void Deletetb003_MUNICIPIO(tb003_MUNICIPIO instance);
    partial void Inserttb004_TIPOS_IDENTIFICACION(tb004_TIPOS_IDENTIFICACION instance);
    partial void Updatetb004_TIPOS_IDENTIFICACION(tb004_TIPOS_IDENTIFICACION instance);
    partial void Deletetb004_TIPOS_IDENTIFICACION(tb004_TIPOS_IDENTIFICACION instance);
    partial void Inserttb005_RRUS(tb005_RRUS instance);
    partial void Updatetb005_RRUS(tb005_RRUS instance);
    partial void Deletetb005_RRUS(tb005_RRUS instance);
    partial void Inserttb006_OPERADOR(tb006_OPERADOR instance);
    partial void Updatetb006_OPERADOR(tb006_OPERADOR instance);
    partial void Deletetb006_OPERADOR(tb006_OPERADOR instance);
    partial void Inserttb007_TIPOS_AUDITORIA(tb007_TIPOS_AUDITORIA instance);
    partial void Updatetb007_TIPOS_AUDITORIA(tb007_TIPOS_AUDITORIA instance);
    partial void Deletetb007_TIPOS_AUDITORIA(tb007_TIPOS_AUDITORIA instance);
    partial void Inserttb008_LOG_AUDITORIA(tb008_LOG_AUDITORIA instance);
    partial void Updatetb008_LOG_AUDITORIA(tb008_LOG_AUDITORIA instance);
    partial void Deletetb008_LOG_AUDITORIA(tb008_LOG_AUDITORIA instance);
    #endregion
		
		public CentralizadorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CentralizadorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CentralizadorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CentralizadorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb001_PAIS> tb001_PAIS
		{
			get
			{
				return this.GetTable<tb001_PAIS>();
			}
		}
		
		public System.Data.Linq.Table<tb009_ENTIDADES> tb009_ENTIDADES
		{
			get
			{
				return this.GetTable<tb009_ENTIDADES>();
			}
		}
		
		public System.Data.Linq.Table<tb002_DEPARTAMENTO> tb002_DEPARTAMENTO
		{
			get
			{
				return this.GetTable<tb002_DEPARTAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<tb003_MUNICIPIO> tb003_MUNICIPIO
		{
			get
			{
				return this.GetTable<tb003_MUNICIPIO>();
			}
		}
		
		public System.Data.Linq.Table<tb004_TIPOS_IDENTIFICACION> tb004_TIPOS_IDENTIFICACION
		{
			get
			{
				return this.GetTable<tb004_TIPOS_IDENTIFICACION>();
			}
		}
		
		public System.Data.Linq.Table<tb005_RRUS> tb005_RRUS
		{
			get
			{
				return this.GetTable<tb005_RRUS>();
			}
		}
		
		public System.Data.Linq.Table<tb006_OPERADOR> tb006_OPERADOR
		{
			get
			{
				return this.GetTable<tb006_OPERADOR>();
			}
		}
		
		public System.Data.Linq.Table<tb007_TIPOS_AUDITORIA> tb007_TIPOS_AUDITORIA
		{
			get
			{
				return this.GetTable<tb007_TIPOS_AUDITORIA>();
			}
		}
		
		public System.Data.Linq.Table<tb008_LOG_AUDITORIA> tb008_LOG_AUDITORIA
		{
			get
			{
				return this.GetTable<tb008_LOG_AUDITORIA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb001_PAIS")]
	public partial class tb001_PAIS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPais;
		
		private string _nombrePais;
		
		private string _codigoDane;
		
		private EntitySet<tb002_DEPARTAMENTO> _tb002_DEPARTAMENTO;
		
		private EntitySet<tb005_RRUS> _tb005_RRUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPaisChanging(int value);
    partial void OnidPaisChanged();
    partial void OnnombrePaisChanging(string value);
    partial void OnnombrePaisChanged();
    partial void OncodigoDaneChanging(string value);
    partial void OncodigoDaneChanged();
    #endregion
		
		public tb001_PAIS()
		{
			this._tb002_DEPARTAMENTO = new EntitySet<tb002_DEPARTAMENTO>(new Action<tb002_DEPARTAMENTO>(this.attach_tb002_DEPARTAMENTO), new Action<tb002_DEPARTAMENTO>(this.detach_tb002_DEPARTAMENTO));
			this._tb005_RRUS = new EntitySet<tb005_RRUS>(new Action<tb005_RRUS>(this.attach_tb005_RRUS), new Action<tb005_RRUS>(this.detach_tb005_RRUS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPais", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idPais
		{
			get
			{
				return this._idPais;
			}
			set
			{
				if ((this._idPais != value))
				{
					this.OnidPaisChanging(value);
					this.SendPropertyChanging();
					this._idPais = value;
					this.SendPropertyChanged("idPais");
					this.OnidPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrePais", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombrePais
		{
			get
			{
				return this._nombrePais;
			}
			set
			{
				if ((this._nombrePais != value))
				{
					this.OnnombrePaisChanging(value);
					this.SendPropertyChanging();
					this._nombrePais = value;
					this.SendPropertyChanged("nombrePais");
					this.OnnombrePaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoDane", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigoDane
		{
			get
			{
				return this._codigoDane;
			}
			set
			{
				if ((this._codigoDane != value))
				{
					this.OncodigoDaneChanging(value);
					this.SendPropertyChanging();
					this._codigoDane = value;
					this.SendPropertyChanged("codigoDane");
					this.OncodigoDaneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb001_PAIS_tb002_DEPARTAMENTO", Storage="_tb002_DEPARTAMENTO", ThisKey="idPais", OtherKey="idPais")]
		public EntitySet<tb002_DEPARTAMENTO> tb002_DEPARTAMENTO
		{
			get
			{
				return this._tb002_DEPARTAMENTO;
			}
			set
			{
				this._tb002_DEPARTAMENTO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb001_PAIS_tb005_RRUS", Storage="_tb005_RRUS", ThisKey="idPais", OtherKey="idPaisNacionalidad")]
		public EntitySet<tb005_RRUS> tb005_RRUS
		{
			get
			{
				return this._tb005_RRUS;
			}
			set
			{
				this._tb005_RRUS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb002_DEPARTAMENTO(tb002_DEPARTAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.tb001_PAIS = this;
		}
		
		private void detach_tb002_DEPARTAMENTO(tb002_DEPARTAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.tb001_PAIS = null;
		}
		
		private void attach_tb005_RRUS(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb001_PAIS = this;
		}
		
		private void detach_tb005_RRUS(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb001_PAIS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb009_ENTIDADES")]
	public partial class tb009_ENTIDADES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEntidades;
		
		private string _nombreEntidad;
		
		private System.Nullable<int> _idTipoIdentificacion;
		
		private string _numeroIdentificacion;
		
		private EntityRef<tb004_TIPOS_IDENTIFICACION> _tb004_TIPOS_IDENTIFICACION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEntidadesChanging(int value);
    partial void OnidEntidadesChanged();
    partial void OnnombreEntidadChanging(string value);
    partial void OnnombreEntidadChanged();
    partial void OnidTipoIdentificacionChanging(System.Nullable<int> value);
    partial void OnidTipoIdentificacionChanged();
    partial void OnnumeroIdentificacionChanging(string value);
    partial void OnnumeroIdentificacionChanged();
    #endregion
		
		public tb009_ENTIDADES()
		{
			this._tb004_TIPOS_IDENTIFICACION = default(EntityRef<tb004_TIPOS_IDENTIFICACION>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEntidades", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEntidades
		{
			get
			{
				return this._idEntidades;
			}
			set
			{
				if ((this._idEntidades != value))
				{
					this.OnidEntidadesChanging(value);
					this.SendPropertyChanging();
					this._idEntidades = value;
					this.SendPropertyChanged("idEntidades");
					this.OnidEntidadesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreEntidad", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nombreEntidad
		{
			get
			{
				return this._nombreEntidad;
			}
			set
			{
				if ((this._nombreEntidad != value))
				{
					this.OnnombreEntidadChanging(value);
					this.SendPropertyChanging();
					this._nombreEntidad = value;
					this.SendPropertyChanged("nombreEntidad");
					this.OnnombreEntidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoIdentificacion", DbType="Int")]
		public System.Nullable<int> idTipoIdentificacion
		{
			get
			{
				return this._idTipoIdentificacion;
			}
			set
			{
				if ((this._idTipoIdentificacion != value))
				{
					if (this._tb004_TIPOS_IDENTIFICACION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipoIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._idTipoIdentificacion = value;
					this.SendPropertyChanged("idTipoIdentificacion");
					this.OnidTipoIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroIdentificacion", DbType="VarChar(50)")]
		public string numeroIdentificacion
		{
			get
			{
				return this._numeroIdentificacion;
			}
			set
			{
				if ((this._numeroIdentificacion != value))
				{
					this.OnnumeroIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._numeroIdentificacion = value;
					this.SendPropertyChanged("numeroIdentificacion");
					this.OnnumeroIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb004_TIPOS_IDENTIFICACION_tb009_ENTIDADES", Storage="_tb004_TIPOS_IDENTIFICACION", ThisKey="idTipoIdentificacion", OtherKey="idTipoIdentificacion", IsForeignKey=true)]
		public tb004_TIPOS_IDENTIFICACION tb004_TIPOS_IDENTIFICACION
		{
			get
			{
				return this._tb004_TIPOS_IDENTIFICACION.Entity;
			}
			set
			{
				tb004_TIPOS_IDENTIFICACION previousValue = this._tb004_TIPOS_IDENTIFICACION.Entity;
				if (((previousValue != value) 
							|| (this._tb004_TIPOS_IDENTIFICACION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb004_TIPOS_IDENTIFICACION.Entity = null;
						previousValue.tb009_ENTIDADES.Remove(this);
					}
					this._tb004_TIPOS_IDENTIFICACION.Entity = value;
					if ((value != null))
					{
						value.tb009_ENTIDADES.Add(this);
						this._idTipoIdentificacion = value.idTipoIdentificacion;
					}
					else
					{
						this._idTipoIdentificacion = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb004_TIPOS_IDENTIFICACION");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb002_DEPARTAMENTO")]
	public partial class tb002_DEPARTAMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDepartamento;
		
		private string _nombreDepartamento;
		
		private int _idPais;
		
		private string _codigoDANE;
		
		private EntitySet<tb003_MUNICIPIO> _tb003_MUNICIPIO;
		
		private EntityRef<tb001_PAIS> _tb001_PAIS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDepartamentoChanging(int value);
    partial void OnidDepartamentoChanged();
    partial void OnnombreDepartamentoChanging(string value);
    partial void OnnombreDepartamentoChanged();
    partial void OnidPaisChanging(int value);
    partial void OnidPaisChanged();
    partial void OncodigoDANEChanging(string value);
    partial void OncodigoDANEChanged();
    #endregion
		
		public tb002_DEPARTAMENTO()
		{
			this._tb003_MUNICIPIO = new EntitySet<tb003_MUNICIPIO>(new Action<tb003_MUNICIPIO>(this.attach_tb003_MUNICIPIO), new Action<tb003_MUNICIPIO>(this.detach_tb003_MUNICIPIO));
			this._tb001_PAIS = default(EntityRef<tb001_PAIS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					this.OnidDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._idDepartamento = value;
					this.SendPropertyChanged("idDepartamento");
					this.OnidDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreDepartamento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombreDepartamento
		{
			get
			{
				return this._nombreDepartamento;
			}
			set
			{
				if ((this._nombreDepartamento != value))
				{
					this.OnnombreDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._nombreDepartamento = value;
					this.SendPropertyChanged("nombreDepartamento");
					this.OnnombreDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPais", DbType="Int NOT NULL")]
		public int idPais
		{
			get
			{
				return this._idPais;
			}
			set
			{
				if ((this._idPais != value))
				{
					if (this._tb001_PAIS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPaisChanging(value);
					this.SendPropertyChanging();
					this._idPais = value;
					this.SendPropertyChanged("idPais");
					this.OnidPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoDANE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigoDANE
		{
			get
			{
				return this._codigoDANE;
			}
			set
			{
				if ((this._codigoDANE != value))
				{
					this.OncodigoDANEChanging(value);
					this.SendPropertyChanging();
					this._codigoDANE = value;
					this.SendPropertyChanged("codigoDANE");
					this.OncodigoDANEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb002_DEPARTAMENTO_tb003_MUNICIPIO", Storage="_tb003_MUNICIPIO", ThisKey="idDepartamento", OtherKey="idDepartamento")]
		public EntitySet<tb003_MUNICIPIO> tb003_MUNICIPIO
		{
			get
			{
				return this._tb003_MUNICIPIO;
			}
			set
			{
				this._tb003_MUNICIPIO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb001_PAIS_tb002_DEPARTAMENTO", Storage="_tb001_PAIS", ThisKey="idPais", OtherKey="idPais", IsForeignKey=true)]
		public tb001_PAIS tb001_PAIS
		{
			get
			{
				return this._tb001_PAIS.Entity;
			}
			set
			{
				tb001_PAIS previousValue = this._tb001_PAIS.Entity;
				if (((previousValue != value) 
							|| (this._tb001_PAIS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb001_PAIS.Entity = null;
						previousValue.tb002_DEPARTAMENTO.Remove(this);
					}
					this._tb001_PAIS.Entity = value;
					if ((value != null))
					{
						value.tb002_DEPARTAMENTO.Add(this);
						this._idPais = value.idPais;
					}
					else
					{
						this._idPais = default(int);
					}
					this.SendPropertyChanged("tb001_PAIS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb003_MUNICIPIO(tb003_MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.tb002_DEPARTAMENTO = this;
		}
		
		private void detach_tb003_MUNICIPIO(tb003_MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.tb002_DEPARTAMENTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb003_MUNICIPIO")]
	public partial class tb003_MUNICIPIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdMunicipio;
		
		private string _nombreMunicipio;
		
		private int _idDepartamento;
		
		private string _codigoDANE;
		
		private EntitySet<tb005_RRUS> _tb005_RRUS;
		
		private EntitySet<tb005_RRUS> _tb005_RRUS1;
		
		private EntitySet<tb005_RRUS> _tb005_RRUS2;
		
		private EntitySet<tb005_RRUS> _tb005_RRUS3;
		
		private EntitySet<tb005_RRUS> _tb005_RRUS4;
		
		private EntityRef<tb002_DEPARTAMENTO> _tb002_DEPARTAMENTO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMunicipioChanging(int value);
    partial void OnIdMunicipioChanged();
    partial void OnnombreMunicipioChanging(string value);
    partial void OnnombreMunicipioChanged();
    partial void OnidDepartamentoChanging(int value);
    partial void OnidDepartamentoChanged();
    partial void OncodigoDANEChanging(string value);
    partial void OncodigoDANEChanged();
    #endregion
		
		public tb003_MUNICIPIO()
		{
			this._tb005_RRUS = new EntitySet<tb005_RRUS>(new Action<tb005_RRUS>(this.attach_tb005_RRUS), new Action<tb005_RRUS>(this.detach_tb005_RRUS));
			this._tb005_RRUS1 = new EntitySet<tb005_RRUS>(new Action<tb005_RRUS>(this.attach_tb005_RRUS1), new Action<tb005_RRUS>(this.detach_tb005_RRUS1));
			this._tb005_RRUS2 = new EntitySet<tb005_RRUS>(new Action<tb005_RRUS>(this.attach_tb005_RRUS2), new Action<tb005_RRUS>(this.detach_tb005_RRUS2));
			this._tb005_RRUS3 = new EntitySet<tb005_RRUS>(new Action<tb005_RRUS>(this.attach_tb005_RRUS3), new Action<tb005_RRUS>(this.detach_tb005_RRUS3));
			this._tb005_RRUS4 = new EntitySet<tb005_RRUS>(new Action<tb005_RRUS>(this.attach_tb005_RRUS4), new Action<tb005_RRUS>(this.detach_tb005_RRUS4));
			this._tb002_DEPARTAMENTO = default(EntityRef<tb002_DEPARTAMENTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMunicipio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdMunicipio
		{
			get
			{
				return this._IdMunicipio;
			}
			set
			{
				if ((this._IdMunicipio != value))
				{
					this.OnIdMunicipioChanging(value);
					this.SendPropertyChanging();
					this._IdMunicipio = value;
					this.SendPropertyChanged("IdMunicipio");
					this.OnIdMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreMunicipio", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombreMunicipio
		{
			get
			{
				return this._nombreMunicipio;
			}
			set
			{
				if ((this._nombreMunicipio != value))
				{
					this.OnnombreMunicipioChanging(value);
					this.SendPropertyChanging();
					this._nombreMunicipio = value;
					this.SendPropertyChanged("nombreMunicipio");
					this.OnnombreMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", DbType="Int NOT NULL")]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					if (this._tb002_DEPARTAMENTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._idDepartamento = value;
					this.SendPropertyChanged("idDepartamento");
					this.OnidDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoDANE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigoDANE
		{
			get
			{
				return this._codigoDANE;
			}
			set
			{
				if ((this._codigoDANE != value))
				{
					this.OncodigoDANEChanging(value);
					this.SendPropertyChanging();
					this._codigoDANE = value;
					this.SendPropertyChanged("codigoDANE");
					this.OncodigoDANEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb003_MUNICIPIO_tb005_RRUS", Storage="_tb005_RRUS", ThisKey="IdMunicipio", OtherKey="idMunicipioExpedicionDocumento")]
		public EntitySet<tb005_RRUS> tb005_RRUS
		{
			get
			{
				return this._tb005_RRUS;
			}
			set
			{
				this._tb005_RRUS.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb003_MUNICIPIO_tb005_RRUS1", Storage="_tb005_RRUS1", ThisKey="IdMunicipio", OtherKey="idMunicipioNotificacionCorrespondencia")]
		public EntitySet<tb005_RRUS> tb005_RRUS1
		{
			get
			{
				return this._tb005_RRUS1;
			}
			set
			{
				this._tb005_RRUS1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb003_MUNICIPIO_tb005_RRUS2", Storage="_tb005_RRUS2", ThisKey="IdMunicipio", OtherKey="idMunicipioLaboral")]
		public EntitySet<tb005_RRUS> tb005_RRUS2
		{
			get
			{
				return this._tb005_RRUS2;
			}
			set
			{
				this._tb005_RRUS2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb003_MUNICIPIO_tb005_RRUS3", Storage="_tb005_RRUS3", ThisKey="IdMunicipio", OtherKey="idMunicipioNacimiento")]
		public EntitySet<tb005_RRUS> tb005_RRUS3
		{
			get
			{
				return this._tb005_RRUS3;
			}
			set
			{
				this._tb005_RRUS3.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb003_MUNICIPIO_tb005_RRUS4", Storage="_tb005_RRUS4", ThisKey="IdMunicipio", OtherKey="idMunicipioResidencia")]
		public EntitySet<tb005_RRUS> tb005_RRUS4
		{
			get
			{
				return this._tb005_RRUS4;
			}
			set
			{
				this._tb005_RRUS4.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb002_DEPARTAMENTO_tb003_MUNICIPIO", Storage="_tb002_DEPARTAMENTO", ThisKey="idDepartamento", OtherKey="idDepartamento", IsForeignKey=true)]
		public tb002_DEPARTAMENTO tb002_DEPARTAMENTO
		{
			get
			{
				return this._tb002_DEPARTAMENTO.Entity;
			}
			set
			{
				tb002_DEPARTAMENTO previousValue = this._tb002_DEPARTAMENTO.Entity;
				if (((previousValue != value) 
							|| (this._tb002_DEPARTAMENTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb002_DEPARTAMENTO.Entity = null;
						previousValue.tb003_MUNICIPIO.Remove(this);
					}
					this._tb002_DEPARTAMENTO.Entity = value;
					if ((value != null))
					{
						value.tb003_MUNICIPIO.Add(this);
						this._idDepartamento = value.idDepartamento;
					}
					else
					{
						this._idDepartamento = default(int);
					}
					this.SendPropertyChanged("tb002_DEPARTAMENTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb005_RRUS(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb003_MUNICIPIO = this;
		}
		
		private void detach_tb005_RRUS(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb003_MUNICIPIO = null;
		}
		
		private void attach_tb005_RRUS1(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb003_MUNICIPIO1 = this;
		}
		
		private void detach_tb005_RRUS1(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb003_MUNICIPIO1 = null;
		}
		
		private void attach_tb005_RRUS2(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb003_MUNICIPIO2 = this;
		}
		
		private void detach_tb005_RRUS2(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb003_MUNICIPIO2 = null;
		}
		
		private void attach_tb005_RRUS3(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb003_MUNICIPIO3 = this;
		}
		
		private void detach_tb005_RRUS3(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb003_MUNICIPIO3 = null;
		}
		
		private void attach_tb005_RRUS4(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb003_MUNICIPIO4 = this;
		}
		
		private void detach_tb005_RRUS4(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb003_MUNICIPIO4 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb004_TIPOS_IDENTIFICACION")]
	public partial class tb004_TIPOS_IDENTIFICACION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipoIdentificacion;
		
		private string _descripcion;
		
		private string _convencion;
		
		private EntitySet<tb009_ENTIDADES> _tb009_ENTIDADES;
		
		private EntitySet<tb005_RRUS> _tb005_RRUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoIdentificacionChanging(int value);
    partial void OnidTipoIdentificacionChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnconvencionChanging(string value);
    partial void OnconvencionChanged();
    #endregion
		
		public tb004_TIPOS_IDENTIFICACION()
		{
			this._tb009_ENTIDADES = new EntitySet<tb009_ENTIDADES>(new Action<tb009_ENTIDADES>(this.attach_tb009_ENTIDADES), new Action<tb009_ENTIDADES>(this.detach_tb009_ENTIDADES));
			this._tb005_RRUS = new EntitySet<tb005_RRUS>(new Action<tb005_RRUS>(this.attach_tb005_RRUS), new Action<tb005_RRUS>(this.detach_tb005_RRUS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoIdentificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTipoIdentificacion
		{
			get
			{
				return this._idTipoIdentificacion;
			}
			set
			{
				if ((this._idTipoIdentificacion != value))
				{
					this.OnidTipoIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._idTipoIdentificacion = value;
					this.SendPropertyChanged("idTipoIdentificacion");
					this.OnidTipoIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_convencion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string convencion
		{
			get
			{
				return this._convencion;
			}
			set
			{
				if ((this._convencion != value))
				{
					this.OnconvencionChanging(value);
					this.SendPropertyChanging();
					this._convencion = value;
					this.SendPropertyChanged("convencion");
					this.OnconvencionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb004_TIPOS_IDENTIFICACION_tb009_ENTIDADES", Storage="_tb009_ENTIDADES", ThisKey="idTipoIdentificacion", OtherKey="idTipoIdentificacion")]
		public EntitySet<tb009_ENTIDADES> tb009_ENTIDADES
		{
			get
			{
				return this._tb009_ENTIDADES;
			}
			set
			{
				this._tb009_ENTIDADES.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb004_TIPOS_IDENTIFICACION_tb005_RRUS", Storage="_tb005_RRUS", ThisKey="idTipoIdentificacion", OtherKey="idTipoIdentificacion")]
		public EntitySet<tb005_RRUS> tb005_RRUS
		{
			get
			{
				return this._tb005_RRUS;
			}
			set
			{
				this._tb005_RRUS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb009_ENTIDADES(tb009_ENTIDADES entity)
		{
			this.SendPropertyChanging();
			entity.tb004_TIPOS_IDENTIFICACION = this;
		}
		
		private void detach_tb009_ENTIDADES(tb009_ENTIDADES entity)
		{
			this.SendPropertyChanging();
			entity.tb004_TIPOS_IDENTIFICACION = null;
		}
		
		private void attach_tb005_RRUS(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb004_TIPOS_IDENTIFICACION = this;
		}
		
		private void detach_tb005_RRUS(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb004_TIPOS_IDENTIFICACION = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb005_RRUS")]
	public partial class tb005_RRUS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idRRUS;
		
		private string _UID;
		
		private int _idTipoIdentificacion;
		
		private string _numeroIdentificacion;
		
		private System.Nullable<int> _idMunicipioExpedicionDocumento;
		
		private System.Nullable<System.DateTime> _fechaExpedicion;
		
		private string _primerApellido;
		
		private string _segundoApellido;
		
		private string _primerNombre;
		
		private string _segundoNombre;
		
		private string _genero;
		
		private System.DateTime _fechaNacimiento;
		
		private int _idMunicipioNacimiento;
		
		private int _idPaisNacionalidad;
		
		private int _idMunicipioResidencia;
		
		private string _direccionResidencia;
		
		private int _idMunicipioNotificacionCorrespondencia;
		
		private string _direccionNotificacionCorrespondencia;
		
		private string _telefono;
		
		private string _correoElectronico;
		
		private int _idMunicipioLaboral;
		
		private string _estadoCivil;
		
		private int _idOperador;
		
		private EntityRef<tb001_PAIS> _tb001_PAIS;
		
		private EntityRef<tb003_MUNICIPIO> _tb003_MUNICIPIO;
		
		private EntityRef<tb003_MUNICIPIO> _tb003_MUNICIPIO1;
		
		private EntityRef<tb003_MUNICIPIO> _tb003_MUNICIPIO2;
		
		private EntityRef<tb003_MUNICIPIO> _tb003_MUNICIPIO3;
		
		private EntityRef<tb003_MUNICIPIO> _tb003_MUNICIPIO4;
		
		private EntityRef<tb004_TIPOS_IDENTIFICACION> _tb004_TIPOS_IDENTIFICACION;
		
		private EntityRef<tb006_OPERADOR> _tb006_OPERADOR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRRUSChanging(long value);
    partial void OnidRRUSChanged();
    partial void OnUIDChanging(string value);
    partial void OnUIDChanged();
    partial void OnidTipoIdentificacionChanging(int value);
    partial void OnidTipoIdentificacionChanged();
    partial void OnnumeroIdentificacionChanging(string value);
    partial void OnnumeroIdentificacionChanged();
    partial void OnidMunicipioExpedicionDocumentoChanging(System.Nullable<int> value);
    partial void OnidMunicipioExpedicionDocumentoChanged();
    partial void OnfechaExpedicionChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaExpedicionChanged();
    partial void OnprimerApellidoChanging(string value);
    partial void OnprimerApellidoChanged();
    partial void OnsegundoApellidoChanging(string value);
    partial void OnsegundoApellidoChanged();
    partial void OnprimerNombreChanging(string value);
    partial void OnprimerNombreChanged();
    partial void OnsegundoNombreChanging(string value);
    partial void OnsegundoNombreChanged();
    partial void OngeneroChanging(string value);
    partial void OngeneroChanged();
    partial void OnfechaNacimientoChanging(System.DateTime value);
    partial void OnfechaNacimientoChanged();
    partial void OnidMunicipioNacimientoChanging(int value);
    partial void OnidMunicipioNacimientoChanged();
    partial void OnidPaisNacionalidadChanging(int value);
    partial void OnidPaisNacionalidadChanged();
    partial void OnidMunicipioResidenciaChanging(int value);
    partial void OnidMunicipioResidenciaChanged();
    partial void OndireccionResidenciaChanging(string value);
    partial void OndireccionResidenciaChanged();
    partial void OnidMunicipioNotificacionCorrespondenciaChanging(int value);
    partial void OnidMunicipioNotificacionCorrespondenciaChanged();
    partial void OndireccionNotificacionCorrespondenciaChanging(string value);
    partial void OndireccionNotificacionCorrespondenciaChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OncorreoElectronicoChanging(string value);
    partial void OncorreoElectronicoChanged();
    partial void OnidMunicipioLaboralChanging(int value);
    partial void OnidMunicipioLaboralChanged();
    partial void OnestadoCivilChanging(string value);
    partial void OnestadoCivilChanged();
    partial void OnidOperadorChanging(int value);
    partial void OnidOperadorChanged();
    #endregion
		
		public tb005_RRUS()
		{
			this._tb001_PAIS = default(EntityRef<tb001_PAIS>);
			this._tb003_MUNICIPIO = default(EntityRef<tb003_MUNICIPIO>);
			this._tb003_MUNICIPIO1 = default(EntityRef<tb003_MUNICIPIO>);
			this._tb003_MUNICIPIO2 = default(EntityRef<tb003_MUNICIPIO>);
			this._tb003_MUNICIPIO3 = default(EntityRef<tb003_MUNICIPIO>);
			this._tb003_MUNICIPIO4 = default(EntityRef<tb003_MUNICIPIO>);
			this._tb004_TIPOS_IDENTIFICACION = default(EntityRef<tb004_TIPOS_IDENTIFICACION>);
			this._tb006_OPERADOR = default(EntityRef<tb006_OPERADOR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRRUS", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long idRRUS
		{
			get
			{
				return this._idRRUS;
			}
			set
			{
				if ((this._idRRUS != value))
				{
					this.OnidRRUSChanging(value);
					this.SendPropertyChanging();
					this._idRRUS = value;
					this.SendPropertyChanged("idRRUS");
					this.OnidRRUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UID", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string UID
		{
			get
			{
				return this._UID;
			}
			set
			{
				if ((this._UID != value))
				{
					this.OnUIDChanging(value);
					this.SendPropertyChanging();
					this._UID = value;
					this.SendPropertyChanged("UID");
					this.OnUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoIdentificacion", DbType="Int NOT NULL")]
		public int idTipoIdentificacion
		{
			get
			{
				return this._idTipoIdentificacion;
			}
			set
			{
				if ((this._idTipoIdentificacion != value))
				{
					if (this._tb004_TIPOS_IDENTIFICACION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipoIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._idTipoIdentificacion = value;
					this.SendPropertyChanged("idTipoIdentificacion");
					this.OnidTipoIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroIdentificacion", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string numeroIdentificacion
		{
			get
			{
				return this._numeroIdentificacion;
			}
			set
			{
				if ((this._numeroIdentificacion != value))
				{
					this.OnnumeroIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._numeroIdentificacion = value;
					this.SendPropertyChanged("numeroIdentificacion");
					this.OnnumeroIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMunicipioExpedicionDocumento", DbType="Int")]
		public System.Nullable<int> idMunicipioExpedicionDocumento
		{
			get
			{
				return this._idMunicipioExpedicionDocumento;
			}
			set
			{
				if ((this._idMunicipioExpedicionDocumento != value))
				{
					if (this._tb003_MUNICIPIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMunicipioExpedicionDocumentoChanging(value);
					this.SendPropertyChanging();
					this._idMunicipioExpedicionDocumento = value;
					this.SendPropertyChanged("idMunicipioExpedicionDocumento");
					this.OnidMunicipioExpedicionDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaExpedicion", DbType="Date")]
		public System.Nullable<System.DateTime> fechaExpedicion
		{
			get
			{
				return this._fechaExpedicion;
			}
			set
			{
				if ((this._fechaExpedicion != value))
				{
					this.OnfechaExpedicionChanging(value);
					this.SendPropertyChanging();
					this._fechaExpedicion = value;
					this.SendPropertyChanged("fechaExpedicion");
					this.OnfechaExpedicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primerApellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string primerApellido
		{
			get
			{
				return this._primerApellido;
			}
			set
			{
				if ((this._primerApellido != value))
				{
					this.OnprimerApellidoChanging(value);
					this.SendPropertyChanging();
					this._primerApellido = value;
					this.SendPropertyChanged("primerApellido");
					this.OnprimerApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundoApellido", DbType="VarChar(50)")]
		public string segundoApellido
		{
			get
			{
				return this._segundoApellido;
			}
			set
			{
				if ((this._segundoApellido != value))
				{
					this.OnsegundoApellidoChanging(value);
					this.SendPropertyChanging();
					this._segundoApellido = value;
					this.SendPropertyChanged("segundoApellido");
					this.OnsegundoApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primerNombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string primerNombre
		{
			get
			{
				return this._primerNombre;
			}
			set
			{
				if ((this._primerNombre != value))
				{
					this.OnprimerNombreChanging(value);
					this.SendPropertyChanging();
					this._primerNombre = value;
					this.SendPropertyChanged("primerNombre");
					this.OnprimerNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundoNombre", DbType="VarChar(50)")]
		public string segundoNombre
		{
			get
			{
				return this._segundoNombre;
			}
			set
			{
				if ((this._segundoNombre != value))
				{
					this.OnsegundoNombreChanging(value);
					this.SendPropertyChanging();
					this._segundoNombre = value;
					this.SendPropertyChanged("segundoNombre");
					this.OnsegundoNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genero", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string genero
		{
			get
			{
				return this._genero;
			}
			set
			{
				if ((this._genero != value))
				{
					this.OngeneroChanging(value);
					this.SendPropertyChanging();
					this._genero = value;
					this.SendPropertyChanged("genero");
					this.OngeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this.OnfechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._fechaNacimiento = value;
					this.SendPropertyChanged("fechaNacimiento");
					this.OnfechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMunicipioNacimiento", DbType="Int NOT NULL")]
		public int idMunicipioNacimiento
		{
			get
			{
				return this._idMunicipioNacimiento;
			}
			set
			{
				if ((this._idMunicipioNacimiento != value))
				{
					if (this._tb003_MUNICIPIO3.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMunicipioNacimientoChanging(value);
					this.SendPropertyChanging();
					this._idMunicipioNacimiento = value;
					this.SendPropertyChanged("idMunicipioNacimiento");
					this.OnidMunicipioNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaisNacionalidad", DbType="Int NOT NULL")]
		public int idPaisNacionalidad
		{
			get
			{
				return this._idPaisNacionalidad;
			}
			set
			{
				if ((this._idPaisNacionalidad != value))
				{
					if (this._tb001_PAIS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPaisNacionalidadChanging(value);
					this.SendPropertyChanging();
					this._idPaisNacionalidad = value;
					this.SendPropertyChanged("idPaisNacionalidad");
					this.OnidPaisNacionalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMunicipioResidencia", DbType="Int NOT NULL")]
		public int idMunicipioResidencia
		{
			get
			{
				return this._idMunicipioResidencia;
			}
			set
			{
				if ((this._idMunicipioResidencia != value))
				{
					if (this._tb003_MUNICIPIO4.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMunicipioResidenciaChanging(value);
					this.SendPropertyChanging();
					this._idMunicipioResidencia = value;
					this.SendPropertyChanged("idMunicipioResidencia");
					this.OnidMunicipioResidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccionResidencia", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string direccionResidencia
		{
			get
			{
				return this._direccionResidencia;
			}
			set
			{
				if ((this._direccionResidencia != value))
				{
					this.OndireccionResidenciaChanging(value);
					this.SendPropertyChanging();
					this._direccionResidencia = value;
					this.SendPropertyChanged("direccionResidencia");
					this.OndireccionResidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMunicipioNotificacionCorrespondencia", DbType="Int NOT NULL")]
		public int idMunicipioNotificacionCorrespondencia
		{
			get
			{
				return this._idMunicipioNotificacionCorrespondencia;
			}
			set
			{
				if ((this._idMunicipioNotificacionCorrespondencia != value))
				{
					if (this._tb003_MUNICIPIO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMunicipioNotificacionCorrespondenciaChanging(value);
					this.SendPropertyChanging();
					this._idMunicipioNotificacionCorrespondencia = value;
					this.SendPropertyChanged("idMunicipioNotificacionCorrespondencia");
					this.OnidMunicipioNotificacionCorrespondenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccionNotificacionCorrespondencia", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string direccionNotificacionCorrespondencia
		{
			get
			{
				return this._direccionNotificacionCorrespondencia;
			}
			set
			{
				if ((this._direccionNotificacionCorrespondencia != value))
				{
					this.OndireccionNotificacionCorrespondenciaChanging(value);
					this.SendPropertyChanging();
					this._direccionNotificacionCorrespondencia = value;
					this.SendPropertyChanged("direccionNotificacionCorrespondencia");
					this.OndireccionNotificacionCorrespondenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correoElectronico", DbType="VarChar(50)")]
		public string correoElectronico
		{
			get
			{
				return this._correoElectronico;
			}
			set
			{
				if ((this._correoElectronico != value))
				{
					this.OncorreoElectronicoChanging(value);
					this.SendPropertyChanging();
					this._correoElectronico = value;
					this.SendPropertyChanged("correoElectronico");
					this.OncorreoElectronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMunicipioLaboral", DbType="Int NOT NULL")]
		public int idMunicipioLaboral
		{
			get
			{
				return this._idMunicipioLaboral;
			}
			set
			{
				if ((this._idMunicipioLaboral != value))
				{
					if (this._tb003_MUNICIPIO2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMunicipioLaboralChanging(value);
					this.SendPropertyChanging();
					this._idMunicipioLaboral = value;
					this.SendPropertyChanged("idMunicipioLaboral");
					this.OnidMunicipioLaboralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadoCivil", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string estadoCivil
		{
			get
			{
				return this._estadoCivil;
			}
			set
			{
				if ((this._estadoCivil != value))
				{
					this.OnestadoCivilChanging(value);
					this.SendPropertyChanging();
					this._estadoCivil = value;
					this.SendPropertyChanged("estadoCivil");
					this.OnestadoCivilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOperador", DbType="Int NOT NULL")]
		public int idOperador
		{
			get
			{
				return this._idOperador;
			}
			set
			{
				if ((this._idOperador != value))
				{
					if (this._tb006_OPERADOR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidOperadorChanging(value);
					this.SendPropertyChanging();
					this._idOperador = value;
					this.SendPropertyChanged("idOperador");
					this.OnidOperadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb001_PAIS_tb005_RRUS", Storage="_tb001_PAIS", ThisKey="idPaisNacionalidad", OtherKey="idPais", IsForeignKey=true)]
		public tb001_PAIS tb001_PAIS
		{
			get
			{
				return this._tb001_PAIS.Entity;
			}
			set
			{
				tb001_PAIS previousValue = this._tb001_PAIS.Entity;
				if (((previousValue != value) 
							|| (this._tb001_PAIS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb001_PAIS.Entity = null;
						previousValue.tb005_RRUS.Remove(this);
					}
					this._tb001_PAIS.Entity = value;
					if ((value != null))
					{
						value.tb005_RRUS.Add(this);
						this._idPaisNacionalidad = value.idPais;
					}
					else
					{
						this._idPaisNacionalidad = default(int);
					}
					this.SendPropertyChanged("tb001_PAIS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb003_MUNICIPIO_tb005_RRUS", Storage="_tb003_MUNICIPIO", ThisKey="idMunicipioExpedicionDocumento", OtherKey="IdMunicipio", IsForeignKey=true)]
		public tb003_MUNICIPIO tb003_MUNICIPIO
		{
			get
			{
				return this._tb003_MUNICIPIO.Entity;
			}
			set
			{
				tb003_MUNICIPIO previousValue = this._tb003_MUNICIPIO.Entity;
				if (((previousValue != value) 
							|| (this._tb003_MUNICIPIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb003_MUNICIPIO.Entity = null;
						previousValue.tb005_RRUS.Remove(this);
					}
					this._tb003_MUNICIPIO.Entity = value;
					if ((value != null))
					{
						value.tb005_RRUS.Add(this);
						this._idMunicipioExpedicionDocumento = value.IdMunicipio;
					}
					else
					{
						this._idMunicipioExpedicionDocumento = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb003_MUNICIPIO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb003_MUNICIPIO_tb005_RRUS1", Storage="_tb003_MUNICIPIO1", ThisKey="idMunicipioNotificacionCorrespondencia", OtherKey="IdMunicipio", IsForeignKey=true)]
		public tb003_MUNICIPIO tb003_MUNICIPIO1
		{
			get
			{
				return this._tb003_MUNICIPIO1.Entity;
			}
			set
			{
				tb003_MUNICIPIO previousValue = this._tb003_MUNICIPIO1.Entity;
				if (((previousValue != value) 
							|| (this._tb003_MUNICIPIO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb003_MUNICIPIO1.Entity = null;
						previousValue.tb005_RRUS1.Remove(this);
					}
					this._tb003_MUNICIPIO1.Entity = value;
					if ((value != null))
					{
						value.tb005_RRUS1.Add(this);
						this._idMunicipioNotificacionCorrespondencia = value.IdMunicipio;
					}
					else
					{
						this._idMunicipioNotificacionCorrespondencia = default(int);
					}
					this.SendPropertyChanged("tb003_MUNICIPIO1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb003_MUNICIPIO_tb005_RRUS2", Storage="_tb003_MUNICIPIO2", ThisKey="idMunicipioLaboral", OtherKey="IdMunicipio", IsForeignKey=true)]
		public tb003_MUNICIPIO tb003_MUNICIPIO2
		{
			get
			{
				return this._tb003_MUNICIPIO2.Entity;
			}
			set
			{
				tb003_MUNICIPIO previousValue = this._tb003_MUNICIPIO2.Entity;
				if (((previousValue != value) 
							|| (this._tb003_MUNICIPIO2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb003_MUNICIPIO2.Entity = null;
						previousValue.tb005_RRUS2.Remove(this);
					}
					this._tb003_MUNICIPIO2.Entity = value;
					if ((value != null))
					{
						value.tb005_RRUS2.Add(this);
						this._idMunicipioLaboral = value.IdMunicipio;
					}
					else
					{
						this._idMunicipioLaboral = default(int);
					}
					this.SendPropertyChanged("tb003_MUNICIPIO2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb003_MUNICIPIO_tb005_RRUS3", Storage="_tb003_MUNICIPIO3", ThisKey="idMunicipioNacimiento", OtherKey="IdMunicipio", IsForeignKey=true)]
		public tb003_MUNICIPIO tb003_MUNICIPIO3
		{
			get
			{
				return this._tb003_MUNICIPIO3.Entity;
			}
			set
			{
				tb003_MUNICIPIO previousValue = this._tb003_MUNICIPIO3.Entity;
				if (((previousValue != value) 
							|| (this._tb003_MUNICIPIO3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb003_MUNICIPIO3.Entity = null;
						previousValue.tb005_RRUS3.Remove(this);
					}
					this._tb003_MUNICIPIO3.Entity = value;
					if ((value != null))
					{
						value.tb005_RRUS3.Add(this);
						this._idMunicipioNacimiento = value.IdMunicipio;
					}
					else
					{
						this._idMunicipioNacimiento = default(int);
					}
					this.SendPropertyChanged("tb003_MUNICIPIO3");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb003_MUNICIPIO_tb005_RRUS4", Storage="_tb003_MUNICIPIO4", ThisKey="idMunicipioResidencia", OtherKey="IdMunicipio", IsForeignKey=true)]
		public tb003_MUNICIPIO tb003_MUNICIPIO4
		{
			get
			{
				return this._tb003_MUNICIPIO4.Entity;
			}
			set
			{
				tb003_MUNICIPIO previousValue = this._tb003_MUNICIPIO4.Entity;
				if (((previousValue != value) 
							|| (this._tb003_MUNICIPIO4.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb003_MUNICIPIO4.Entity = null;
						previousValue.tb005_RRUS4.Remove(this);
					}
					this._tb003_MUNICIPIO4.Entity = value;
					if ((value != null))
					{
						value.tb005_RRUS4.Add(this);
						this._idMunicipioResidencia = value.IdMunicipio;
					}
					else
					{
						this._idMunicipioResidencia = default(int);
					}
					this.SendPropertyChanged("tb003_MUNICIPIO4");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb004_TIPOS_IDENTIFICACION_tb005_RRUS", Storage="_tb004_TIPOS_IDENTIFICACION", ThisKey="idTipoIdentificacion", OtherKey="idTipoIdentificacion", IsForeignKey=true)]
		public tb004_TIPOS_IDENTIFICACION tb004_TIPOS_IDENTIFICACION
		{
			get
			{
				return this._tb004_TIPOS_IDENTIFICACION.Entity;
			}
			set
			{
				tb004_TIPOS_IDENTIFICACION previousValue = this._tb004_TIPOS_IDENTIFICACION.Entity;
				if (((previousValue != value) 
							|| (this._tb004_TIPOS_IDENTIFICACION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb004_TIPOS_IDENTIFICACION.Entity = null;
						previousValue.tb005_RRUS.Remove(this);
					}
					this._tb004_TIPOS_IDENTIFICACION.Entity = value;
					if ((value != null))
					{
						value.tb005_RRUS.Add(this);
						this._idTipoIdentificacion = value.idTipoIdentificacion;
					}
					else
					{
						this._idTipoIdentificacion = default(int);
					}
					this.SendPropertyChanged("tb004_TIPOS_IDENTIFICACION");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb006_OPERADOR_tb005_RRUS", Storage="_tb006_OPERADOR", ThisKey="idOperador", OtherKey="idOperador", IsForeignKey=true)]
		public tb006_OPERADOR tb006_OPERADOR
		{
			get
			{
				return this._tb006_OPERADOR.Entity;
			}
			set
			{
				tb006_OPERADOR previousValue = this._tb006_OPERADOR.Entity;
				if (((previousValue != value) 
							|| (this._tb006_OPERADOR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb006_OPERADOR.Entity = null;
						previousValue.tb005_RRUS.Remove(this);
					}
					this._tb006_OPERADOR.Entity = value;
					if ((value != null))
					{
						value.tb005_RRUS.Add(this);
						this._idOperador = value.idOperador;
					}
					else
					{
						this._idOperador = default(int);
					}
					this.SendPropertyChanged("tb006_OPERADOR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb006_OPERADOR")]
	public partial class tb006_OPERADOR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idOperador;
		
		private string _nombreOperador;
		
		private int _tipoIdentificacion;
		
		private string _numeroIdentificacion;
		
		private EntitySet<tb005_RRUS> _tb005_RRUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidOperadorChanging(int value);
    partial void OnidOperadorChanged();
    partial void OnnombreOperadorChanging(string value);
    partial void OnnombreOperadorChanged();
    partial void OntipoIdentificacionChanging(int value);
    partial void OntipoIdentificacionChanged();
    partial void OnnumeroIdentificacionChanging(string value);
    partial void OnnumeroIdentificacionChanged();
    #endregion
		
		public tb006_OPERADOR()
		{
			this._tb005_RRUS = new EntitySet<tb005_RRUS>(new Action<tb005_RRUS>(this.attach_tb005_RRUS), new Action<tb005_RRUS>(this.detach_tb005_RRUS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOperador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idOperador
		{
			get
			{
				return this._idOperador;
			}
			set
			{
				if ((this._idOperador != value))
				{
					this.OnidOperadorChanging(value);
					this.SendPropertyChanging();
					this._idOperador = value;
					this.SendPropertyChanged("idOperador");
					this.OnidOperadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreOperador", DbType="VarChar(100)")]
		public string nombreOperador
		{
			get
			{
				return this._nombreOperador;
			}
			set
			{
				if ((this._nombreOperador != value))
				{
					this.OnnombreOperadorChanging(value);
					this.SendPropertyChanging();
					this._nombreOperador = value;
					this.SendPropertyChanged("nombreOperador");
					this.OnnombreOperadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoIdentificacion", DbType="Int NOT NULL")]
		public int tipoIdentificacion
		{
			get
			{
				return this._tipoIdentificacion;
			}
			set
			{
				if ((this._tipoIdentificacion != value))
				{
					this.OntipoIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._tipoIdentificacion = value;
					this.SendPropertyChanged("tipoIdentificacion");
					this.OntipoIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroIdentificacion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string numeroIdentificacion
		{
			get
			{
				return this._numeroIdentificacion;
			}
			set
			{
				if ((this._numeroIdentificacion != value))
				{
					this.OnnumeroIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._numeroIdentificacion = value;
					this.SendPropertyChanged("numeroIdentificacion");
					this.OnnumeroIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb006_OPERADOR_tb005_RRUS", Storage="_tb005_RRUS", ThisKey="idOperador", OtherKey="idOperador")]
		public EntitySet<tb005_RRUS> tb005_RRUS
		{
			get
			{
				return this._tb005_RRUS;
			}
			set
			{
				this._tb005_RRUS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb005_RRUS(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb006_OPERADOR = this;
		}
		
		private void detach_tb005_RRUS(tb005_RRUS entity)
		{
			this.SendPropertyChanging();
			entity.tb006_OPERADOR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb007_TIPOS_AUDITORIA")]
	public partial class tb007_TIPOS_AUDITORIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idAuditoria;
		
		private string _nombreAuditoria;
		
		private string _descripcionAuditoria;
		
		private EntitySet<tb008_LOG_AUDITORIA> _tb008_LOG_AUDITORIA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidAuditoriaChanging(int value);
    partial void OnidAuditoriaChanged();
    partial void OnnombreAuditoriaChanging(string value);
    partial void OnnombreAuditoriaChanged();
    partial void OndescripcionAuditoriaChanging(string value);
    partial void OndescripcionAuditoriaChanged();
    #endregion
		
		public tb007_TIPOS_AUDITORIA()
		{
			this._tb008_LOG_AUDITORIA = new EntitySet<tb008_LOG_AUDITORIA>(new Action<tb008_LOG_AUDITORIA>(this.attach_tb008_LOG_AUDITORIA), new Action<tb008_LOG_AUDITORIA>(this.detach_tb008_LOG_AUDITORIA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAuditoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idAuditoria
		{
			get
			{
				return this._idAuditoria;
			}
			set
			{
				if ((this._idAuditoria != value))
				{
					this.OnidAuditoriaChanging(value);
					this.SendPropertyChanging();
					this._idAuditoria = value;
					this.SendPropertyChanged("idAuditoria");
					this.OnidAuditoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreAuditoria", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string nombreAuditoria
		{
			get
			{
				return this._nombreAuditoria;
			}
			set
			{
				if ((this._nombreAuditoria != value))
				{
					this.OnnombreAuditoriaChanging(value);
					this.SendPropertyChanging();
					this._nombreAuditoria = value;
					this.SendPropertyChanged("nombreAuditoria");
					this.OnnombreAuditoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionAuditoria", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string descripcionAuditoria
		{
			get
			{
				return this._descripcionAuditoria;
			}
			set
			{
				if ((this._descripcionAuditoria != value))
				{
					this.OndescripcionAuditoriaChanging(value);
					this.SendPropertyChanging();
					this._descripcionAuditoria = value;
					this.SendPropertyChanged("descripcionAuditoria");
					this.OndescripcionAuditoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb007_TIPOS_AUDITORIA_tb008_LOG_AUDITORIA", Storage="_tb008_LOG_AUDITORIA", ThisKey="idAuditoria", OtherKey="idAuditoria")]
		public EntitySet<tb008_LOG_AUDITORIA> tb008_LOG_AUDITORIA
		{
			get
			{
				return this._tb008_LOG_AUDITORIA;
			}
			set
			{
				this._tb008_LOG_AUDITORIA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb008_LOG_AUDITORIA(tb008_LOG_AUDITORIA entity)
		{
			this.SendPropertyChanging();
			entity.tb007_TIPOS_AUDITORIA = this;
		}
		
		private void detach_tb008_LOG_AUDITORIA(tb008_LOG_AUDITORIA entity)
		{
			this.SendPropertyChanging();
			entity.tb007_TIPOS_AUDITORIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb008_LOG_AUDITORIA")]
	public partial class tb008_LOG_AUDITORIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idLogAuditoria;
		
		private int _idAuditoria;
		
		private int _idOperador;
		
		private System.DateTime _fechaLog;
		
		private string _comentarios;
		
		private EntityRef<tb007_TIPOS_AUDITORIA> _tb007_TIPOS_AUDITORIA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidLogAuditoriaChanging(long value);
    partial void OnidLogAuditoriaChanged();
    partial void OnidAuditoriaChanging(int value);
    partial void OnidAuditoriaChanged();
    partial void OnidOperadorChanging(int value);
    partial void OnidOperadorChanged();
    partial void OnfechaLogChanging(System.DateTime value);
    partial void OnfechaLogChanged();
    partial void OncomentariosChanging(string value);
    partial void OncomentariosChanged();
    #endregion
		
		public tb008_LOG_AUDITORIA()
		{
			this._tb007_TIPOS_AUDITORIA = default(EntityRef<tb007_TIPOS_AUDITORIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLogAuditoria", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long idLogAuditoria
		{
			get
			{
				return this._idLogAuditoria;
			}
			set
			{
				if ((this._idLogAuditoria != value))
				{
					this.OnidLogAuditoriaChanging(value);
					this.SendPropertyChanging();
					this._idLogAuditoria = value;
					this.SendPropertyChanged("idLogAuditoria");
					this.OnidLogAuditoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAuditoria", DbType="Int NOT NULL")]
		public int idAuditoria
		{
			get
			{
				return this._idAuditoria;
			}
			set
			{
				if ((this._idAuditoria != value))
				{
					if (this._tb007_TIPOS_AUDITORIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidAuditoriaChanging(value);
					this.SendPropertyChanging();
					this._idAuditoria = value;
					this.SendPropertyChanged("idAuditoria");
					this.OnidAuditoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOperador", DbType="Int NOT NULL")]
		public int idOperador
		{
			get
			{
				return this._idOperador;
			}
			set
			{
				if ((this._idOperador != value))
				{
					this.OnidOperadorChanging(value);
					this.SendPropertyChanging();
					this._idOperador = value;
					this.SendPropertyChanged("idOperador");
					this.OnidOperadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaLog", DbType="DateTime NOT NULL")]
		public System.DateTime fechaLog
		{
			get
			{
				return this._fechaLog;
			}
			set
			{
				if ((this._fechaLog != value))
				{
					this.OnfechaLogChanging(value);
					this.SendPropertyChanging();
					this._fechaLog = value;
					this.SendPropertyChanged("fechaLog");
					this.OnfechaLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentarios", DbType="VarChar(1500) NOT NULL", CanBeNull=false)]
		public string comentarios
		{
			get
			{
				return this._comentarios;
			}
			set
			{
				if ((this._comentarios != value))
				{
					this.OncomentariosChanging(value);
					this.SendPropertyChanging();
					this._comentarios = value;
					this.SendPropertyChanged("comentarios");
					this.OncomentariosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb007_TIPOS_AUDITORIA_tb008_LOG_AUDITORIA", Storage="_tb007_TIPOS_AUDITORIA", ThisKey="idAuditoria", OtherKey="idAuditoria", IsForeignKey=true)]
		public tb007_TIPOS_AUDITORIA tb007_TIPOS_AUDITORIA
		{
			get
			{
				return this._tb007_TIPOS_AUDITORIA.Entity;
			}
			set
			{
				tb007_TIPOS_AUDITORIA previousValue = this._tb007_TIPOS_AUDITORIA.Entity;
				if (((previousValue != value) 
							|| (this._tb007_TIPOS_AUDITORIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb007_TIPOS_AUDITORIA.Entity = null;
						previousValue.tb008_LOG_AUDITORIA.Remove(this);
					}
					this._tb007_TIPOS_AUDITORIA.Entity = value;
					if ((value != null))
					{
						value.tb008_LOG_AUDITORIA.Add(this);
						this._idAuditoria = value.idAuditoria;
					}
					else
					{
						this._idAuditoria = default(int);
					}
					this.SendPropertyChanged("tb007_TIPOS_AUDITORIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
