#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniandes.Controlador
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OperadorCarpeta")]
	public partial class OperadorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttb001_PAIS(tb001_PAIS instance);
    partial void Updatetb001_PAIS(tb001_PAIS instance);
    partial void Deletetb001_PAIS(tb001_PAIS instance);
    partial void InserttblEstadoMensajes(tblEstadoMensajes instance);
    partial void UpdatetblEstadoMensajes(tblEstadoMensajes instance);
    partial void DeletetblEstadoMensajes(tblEstadoMensajes instance);
    partial void Inserttb002_DEPARTAMENTO(tb002_DEPARTAMENTO instance);
    partial void Updatetb002_DEPARTAMENTO(tb002_DEPARTAMENTO instance);
    partial void Deletetb002_DEPARTAMENTO(tb002_DEPARTAMENTO instance);
    partial void Inserttb003_MUNICIPIO(tb003_MUNICIPIO instance);
    partial void Updatetb003_MUNICIPIO(tb003_MUNICIPIO instance);
    partial void Deletetb003_MUNICIPIO(tb003_MUNICIPIO instance);
    partial void Inserttbl_metadataArchivos(tbl_metadataArchivos instance);
    partial void Updatetbl_metadataArchivos(tbl_metadataArchivos instance);
    partial void Deletetbl_metadataArchivos(tbl_metadataArchivos instance);
    partial void Inserttbl_tipoDocumento(tbl_tipoDocumento instance);
    partial void Updatetbl_tipoDocumento(tbl_tipoDocumento instance);
    partial void Deletetbl_tipoDocumento(tbl_tipoDocumento instance);
    partial void Inserttbl_tipoId(tbl_tipoId instance);
    partial void Updatetbl_tipoId(tbl_tipoId instance);
    partial void Deletetbl_tipoId(tbl_tipoId instance);
    partial void Inserttbl_TipologiaDocumental(tbl_TipologiaDocumental instance);
    partial void Updatetbl_TipologiaDocumental(tbl_TipologiaDocumental instance);
    partial void Deletetbl_TipologiaDocumental(tbl_TipologiaDocumental instance);
    partial void Inserttbl_usuarios(tbl_usuarios instance);
    partial void Updatetbl_usuarios(tbl_usuarios instance);
    partial void Deletetbl_usuarios(tbl_usuarios instance);
    partial void InserttblBandejaNotificaciones(tblBandejaNotificaciones instance);
    partial void UpdatetblBandejaNotificaciones(tblBandejaNotificaciones instance);
    partial void DeletetblBandejaNotificaciones(tblBandejaNotificaciones instance);
    partial void InserttblCarpetaPersonal(tblCarpetaPersonal instance);
    partial void UpdatetblCarpetaPersonal(tblCarpetaPersonal instance);
    partial void DeletetblCarpetaPersonal(tblCarpetaPersonal instance);
    partial void InserttblDocumentosAdjuntos(tblDocumentosAdjuntos instance);
    partial void UpdatetblDocumentosAdjuntos(tblDocumentosAdjuntos instance);
    partial void DeletetblDocumentosAdjuntos(tblDocumentosAdjuntos instance);
    #endregion
		
		public OperadorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperadorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperadorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperadorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb001_PAIS> tb001_PAIS
		{
			get
			{
				return this.GetTable<tb001_PAIS>();
			}
		}
		
		public System.Data.Linq.Table<tblEstadoMensajes> tblEstadoMensajes
		{
			get
			{
				return this.GetTable<tblEstadoMensajes>();
			}
		}
		
		public System.Data.Linq.Table<tb002_DEPARTAMENTO> tb002_DEPARTAMENTO
		{
			get
			{
				return this.GetTable<tb002_DEPARTAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<tb003_MUNICIPIO> tb003_MUNICIPIO
		{
			get
			{
				return this.GetTable<tb003_MUNICIPIO>();
			}
		}
		
		public System.Data.Linq.Table<tbl_metadataArchivos> tbl_metadataArchivos
		{
			get
			{
				return this.GetTable<tbl_metadataArchivos>();
			}
		}
		
		public System.Data.Linq.Table<tbl_tipoDocumento> tbl_tipoDocumento
		{
			get
			{
				return this.GetTable<tbl_tipoDocumento>();
			}
		}
		
		public System.Data.Linq.Table<tbl_tipoId> tbl_tipoId
		{
			get
			{
				return this.GetTable<tbl_tipoId>();
			}
		}
		
		public System.Data.Linq.Table<tbl_TipologiaDocumental> tbl_TipologiaDocumental
		{
			get
			{
				return this.GetTable<tbl_TipologiaDocumental>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuarios> tbl_usuarios
		{
			get
			{
				return this.GetTable<tbl_usuarios>();
			}
		}
		
		public System.Data.Linq.Table<tblBandejaNotificaciones> tblBandejaNotificaciones
		{
			get
			{
				return this.GetTable<tblBandejaNotificaciones>();
			}
		}
		
		public System.Data.Linq.Table<tblCarpetaPersonal> tblCarpetaPersonal
		{
			get
			{
				return this.GetTable<tblCarpetaPersonal>();
			}
		}
		
		public System.Data.Linq.Table<tblDocumentosAdjuntos> tblDocumentosAdjuntos
		{
			get
			{
				return this.GetTable<tblDocumentosAdjuntos>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb001_PAIS")]
	public partial class tb001_PAIS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPais;
		
		private string _nombrePais;
		
		private string _codigoDane;
		
		private EntitySet<tb002_DEPARTAMENTO> _tb002_DEPARTAMENTO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPaisChanging(int value);
    partial void OnidPaisChanged();
    partial void OnnombrePaisChanging(string value);
    partial void OnnombrePaisChanged();
    partial void OncodigoDaneChanging(string value);
    partial void OncodigoDaneChanged();
    #endregion
		
		public tb001_PAIS()
		{
			this._tb002_DEPARTAMENTO = new EntitySet<tb002_DEPARTAMENTO>(new Action<tb002_DEPARTAMENTO>(this.attach_tb002_DEPARTAMENTO), new Action<tb002_DEPARTAMENTO>(this.detach_tb002_DEPARTAMENTO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPais", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idPais
		{
			get
			{
				return this._idPais;
			}
			set
			{
				if ((this._idPais != value))
				{
					this.OnidPaisChanging(value);
					this.SendPropertyChanging();
					this._idPais = value;
					this.SendPropertyChanged("idPais");
					this.OnidPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrePais", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombrePais
		{
			get
			{
				return this._nombrePais;
			}
			set
			{
				if ((this._nombrePais != value))
				{
					this.OnnombrePaisChanging(value);
					this.SendPropertyChanging();
					this._nombrePais = value;
					this.SendPropertyChanged("nombrePais");
					this.OnnombrePaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoDane", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigoDane
		{
			get
			{
				return this._codigoDane;
			}
			set
			{
				if ((this._codigoDane != value))
				{
					this.OncodigoDaneChanging(value);
					this.SendPropertyChanging();
					this._codigoDane = value;
					this.SendPropertyChanged("codigoDane");
					this.OncodigoDaneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb001_PAIS_tb002_DEPARTAMENTO", Storage="_tb002_DEPARTAMENTO", ThisKey="idPais", OtherKey="idPais")]
		public EntitySet<tb002_DEPARTAMENTO> tb002_DEPARTAMENTO
		{
			get
			{
				return this._tb002_DEPARTAMENTO;
			}
			set
			{
				this._tb002_DEPARTAMENTO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb002_DEPARTAMENTO(tb002_DEPARTAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.tb001_PAIS = this;
		}
		
		private void detach_tb002_DEPARTAMENTO(tb002_DEPARTAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.tb001_PAIS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEstadoMensajes")]
	public partial class tblEstadoMensajes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEstadoMensajes;
		
		private string _Estado;
		
		private string _Descripcion;
		
		private EntitySet<tblBandejaNotificaciones> _tblBandejaNotificaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEstadoMensajesChanging(int value);
    partial void OnidEstadoMensajesChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public tblEstadoMensajes()
		{
			this._tblBandejaNotificaciones = new EntitySet<tblBandejaNotificaciones>(new Action<tblBandejaNotificaciones>(this.attach_tblBandejaNotificaciones), new Action<tblBandejaNotificaciones>(this.detach_tblBandejaNotificaciones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstadoMensajes", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEstadoMensajes
		{
			get
			{
				return this._idEstadoMensajes;
			}
			set
			{
				if ((this._idEstadoMensajes != value))
				{
					this.OnidEstadoMensajesChanging(value);
					this.SendPropertyChanging();
					this._idEstadoMensajes = value;
					this.SendPropertyChanged("idEstadoMensajes");
					this.OnidEstadoMensajesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEstadoMensajes_tblBandejaNotificaciones", Storage="_tblBandejaNotificaciones", ThisKey="idEstadoMensajes", OtherKey="Estado")]
		public EntitySet<tblBandejaNotificaciones> tblBandejaNotificaciones
		{
			get
			{
				return this._tblBandejaNotificaciones;
			}
			set
			{
				this._tblBandejaNotificaciones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblBandejaNotificaciones(tblBandejaNotificaciones entity)
		{
			this.SendPropertyChanging();
			entity.tblEstadoMensajes = this;
		}
		
		private void detach_tblBandejaNotificaciones(tblBandejaNotificaciones entity)
		{
			this.SendPropertyChanging();
			entity.tblEstadoMensajes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb002_DEPARTAMENTO")]
	public partial class tb002_DEPARTAMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDepartamento;
		
		private string _nombreDepartamento;
		
		private int _idPais;
		
		private string _codigoDANE;
		
		private EntitySet<tb003_MUNICIPIO> _tb003_MUNICIPIO;
		
		private EntityRef<tb001_PAIS> _tb001_PAIS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDepartamentoChanging(int value);
    partial void OnidDepartamentoChanged();
    partial void OnnombreDepartamentoChanging(string value);
    partial void OnnombreDepartamentoChanged();
    partial void OnidPaisChanging(int value);
    partial void OnidPaisChanged();
    partial void OncodigoDANEChanging(string value);
    partial void OncodigoDANEChanged();
    #endregion
		
		public tb002_DEPARTAMENTO()
		{
			this._tb003_MUNICIPIO = new EntitySet<tb003_MUNICIPIO>(new Action<tb003_MUNICIPIO>(this.attach_tb003_MUNICIPIO), new Action<tb003_MUNICIPIO>(this.detach_tb003_MUNICIPIO));
			this._tb001_PAIS = default(EntityRef<tb001_PAIS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					this.OnidDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._idDepartamento = value;
					this.SendPropertyChanged("idDepartamento");
					this.OnidDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreDepartamento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombreDepartamento
		{
			get
			{
				return this._nombreDepartamento;
			}
			set
			{
				if ((this._nombreDepartamento != value))
				{
					this.OnnombreDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._nombreDepartamento = value;
					this.SendPropertyChanged("nombreDepartamento");
					this.OnnombreDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPais", DbType="Int NOT NULL")]
		public int idPais
		{
			get
			{
				return this._idPais;
			}
			set
			{
				if ((this._idPais != value))
				{
					if (this._tb001_PAIS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPaisChanging(value);
					this.SendPropertyChanging();
					this._idPais = value;
					this.SendPropertyChanged("idPais");
					this.OnidPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoDANE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigoDANE
		{
			get
			{
				return this._codigoDANE;
			}
			set
			{
				if ((this._codigoDANE != value))
				{
					this.OncodigoDANEChanging(value);
					this.SendPropertyChanging();
					this._codigoDANE = value;
					this.SendPropertyChanged("codigoDANE");
					this.OncodigoDANEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb002_DEPARTAMENTO_tb003_MUNICIPIO", Storage="_tb003_MUNICIPIO", ThisKey="idDepartamento", OtherKey="idDepartamento")]
		public EntitySet<tb003_MUNICIPIO> tb003_MUNICIPIO
		{
			get
			{
				return this._tb003_MUNICIPIO;
			}
			set
			{
				this._tb003_MUNICIPIO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb001_PAIS_tb002_DEPARTAMENTO", Storage="_tb001_PAIS", ThisKey="idPais", OtherKey="idPais", IsForeignKey=true)]
		public tb001_PAIS tb001_PAIS
		{
			get
			{
				return this._tb001_PAIS.Entity;
			}
			set
			{
				tb001_PAIS previousValue = this._tb001_PAIS.Entity;
				if (((previousValue != value) 
							|| (this._tb001_PAIS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb001_PAIS.Entity = null;
						previousValue.tb002_DEPARTAMENTO.Remove(this);
					}
					this._tb001_PAIS.Entity = value;
					if ((value != null))
					{
						value.tb002_DEPARTAMENTO.Add(this);
						this._idPais = value.idPais;
					}
					else
					{
						this._idPais = default(int);
					}
					this.SendPropertyChanged("tb001_PAIS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb003_MUNICIPIO(tb003_MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.tb002_DEPARTAMENTO = this;
		}
		
		private void detach_tb003_MUNICIPIO(tb003_MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.tb002_DEPARTAMENTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb003_MUNICIPIO")]
	public partial class tb003_MUNICIPIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdMunicipio;
		
		private string _nombreMunicipio;
		
		private int _idDepartamento;
		
		private string _codigoDANE;
		
		private EntityRef<tb002_DEPARTAMENTO> _tb002_DEPARTAMENTO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMunicipioChanging(int value);
    partial void OnIdMunicipioChanged();
    partial void OnnombreMunicipioChanging(string value);
    partial void OnnombreMunicipioChanged();
    partial void OnidDepartamentoChanging(int value);
    partial void OnidDepartamentoChanged();
    partial void OncodigoDANEChanging(string value);
    partial void OncodigoDANEChanged();
    #endregion
		
		public tb003_MUNICIPIO()
		{
			this._tb002_DEPARTAMENTO = default(EntityRef<tb002_DEPARTAMENTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMunicipio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdMunicipio
		{
			get
			{
				return this._IdMunicipio;
			}
			set
			{
				if ((this._IdMunicipio != value))
				{
					this.OnIdMunicipioChanging(value);
					this.SendPropertyChanging();
					this._IdMunicipio = value;
					this.SendPropertyChanged("IdMunicipio");
					this.OnIdMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreMunicipio", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombreMunicipio
		{
			get
			{
				return this._nombreMunicipio;
			}
			set
			{
				if ((this._nombreMunicipio != value))
				{
					this.OnnombreMunicipioChanging(value);
					this.SendPropertyChanging();
					this._nombreMunicipio = value;
					this.SendPropertyChanged("nombreMunicipio");
					this.OnnombreMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", DbType="Int NOT NULL")]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					if (this._tb002_DEPARTAMENTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._idDepartamento = value;
					this.SendPropertyChanged("idDepartamento");
					this.OnidDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoDANE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigoDANE
		{
			get
			{
				return this._codigoDANE;
			}
			set
			{
				if ((this._codigoDANE != value))
				{
					this.OncodigoDANEChanging(value);
					this.SendPropertyChanging();
					this._codigoDANE = value;
					this.SendPropertyChanged("codigoDANE");
					this.OncodigoDANEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb002_DEPARTAMENTO_tb003_MUNICIPIO", Storage="_tb002_DEPARTAMENTO", ThisKey="idDepartamento", OtherKey="idDepartamento", IsForeignKey=true)]
		public tb002_DEPARTAMENTO tb002_DEPARTAMENTO
		{
			get
			{
				return this._tb002_DEPARTAMENTO.Entity;
			}
			set
			{
				tb002_DEPARTAMENTO previousValue = this._tb002_DEPARTAMENTO.Entity;
				if (((previousValue != value) 
							|| (this._tb002_DEPARTAMENTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb002_DEPARTAMENTO.Entity = null;
						previousValue.tb003_MUNICIPIO.Remove(this);
					}
					this._tb002_DEPARTAMENTO.Entity = value;
					if ((value != null))
					{
						value.tb003_MUNICIPIO.Add(this);
						this._idDepartamento = value.idDepartamento;
					}
					else
					{
						this._idDepartamento = default(int);
					}
					this.SendPropertyChanged("tb002_DEPARTAMENTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_metadataArchivos")]
	public partial class tbl_metadataArchivos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _idDMtadataArchivo;
		
		private System.Nullable<decimal> _idCarpetaPersonal;
		
		private string _userIdApplicacion;
		
		private string _nombre;
		
		private string _nombre_generado;
		
		private string _extension;
		
		private string _autor;
		
		private System.DateTime _fecha_Cargue;
		
		private System.Nullable<System.DateTime> _fecha_modificacion;
		
		private decimal _idTipoDocumento;
		
		private string _tamanio;
		
		private EntitySet<tblDocumentosAdjuntos> _tblDocumentosAdjuntos;
		
		private EntityRef<tbl_tipoDocumento> _tbl_tipoDocumento;
		
		private EntityRef<tblCarpetaPersonal> _tblCarpetaPersonal;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDMtadataArchivoChanging(System.Guid value);
    partial void OnidDMtadataArchivoChanged();
    partial void OnidCarpetaPersonalChanging(System.Nullable<decimal> value);
    partial void OnidCarpetaPersonalChanged();
    partial void OnuserIdApplicacionChanging(string value);
    partial void OnuserIdApplicacionChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onnombre_generadoChanging(string value);
    partial void Onnombre_generadoChanged();
    partial void OnextensionChanging(string value);
    partial void OnextensionChanged();
    partial void OnautorChanging(string value);
    partial void OnautorChanged();
    partial void Onfecha_CargueChanging(System.DateTime value);
    partial void Onfecha_CargueChanged();
    partial void Onfecha_modificacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_modificacionChanged();
    partial void OnidTipoDocumentoChanging(decimal value);
    partial void OnidTipoDocumentoChanged();
    partial void OntamanioChanging(string value);
    partial void OntamanioChanged();
    #endregion
		
		public tbl_metadataArchivos()
		{
			this._tblDocumentosAdjuntos = new EntitySet<tblDocumentosAdjuntos>(new Action<tblDocumentosAdjuntos>(this.attach_tblDocumentosAdjuntos), new Action<tblDocumentosAdjuntos>(this.detach_tblDocumentosAdjuntos));
			this._tbl_tipoDocumento = default(EntityRef<tbl_tipoDocumento>);
			this._tblCarpetaPersonal = default(EntityRef<tblCarpetaPersonal>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDMtadataArchivo", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid idDMtadataArchivo
		{
			get
			{
				return this._idDMtadataArchivo;
			}
			set
			{
				if ((this._idDMtadataArchivo != value))
				{
					this.OnidDMtadataArchivoChanging(value);
					this.SendPropertyChanging();
					this._idDMtadataArchivo = value;
					this.SendPropertyChanged("idDMtadataArchivo");
					this.OnidDMtadataArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarpetaPersonal", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> idCarpetaPersonal
		{
			get
			{
				return this._idCarpetaPersonal;
			}
			set
			{
				if ((this._idCarpetaPersonal != value))
				{
					if (this._tblCarpetaPersonal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCarpetaPersonalChanging(value);
					this.SendPropertyChanging();
					this._idCarpetaPersonal = value;
					this.SendPropertyChanged("idCarpetaPersonal");
					this.OnidCarpetaPersonalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userIdApplicacion", DbType="VarChar(MAX)")]
		public string userIdApplicacion
		{
			get
			{
				return this._userIdApplicacion;
			}
			set
			{
				if ((this._userIdApplicacion != value))
				{
					this.OnuserIdApplicacionChanging(value);
					this.SendPropertyChanging();
					this._userIdApplicacion = value;
					this.SendPropertyChanged("userIdApplicacion");
					this.OnuserIdApplicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_generado", DbType="VarChar(500)")]
		public string nombre_generado
		{
			get
			{
				return this._nombre_generado;
			}
			set
			{
				if ((this._nombre_generado != value))
				{
					this.Onnombre_generadoChanging(value);
					this.SendPropertyChanging();
					this._nombre_generado = value;
					this.SendPropertyChanged("nombre_generado");
					this.Onnombre_generadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extension", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string extension
		{
			get
			{
				return this._extension;
			}
			set
			{
				if ((this._extension != value))
				{
					this.OnextensionChanging(value);
					this.SendPropertyChanging();
					this._extension = value;
					this.SendPropertyChanged("extension");
					this.OnextensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_autor", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string autor
		{
			get
			{
				return this._autor;
			}
			set
			{
				if ((this._autor != value))
				{
					this.OnautorChanging(value);
					this.SendPropertyChanging();
					this._autor = value;
					this.SendPropertyChanged("autor");
					this.OnautorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_Cargue", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_Cargue
		{
			get
			{
				return this._fecha_Cargue;
			}
			set
			{
				if ((this._fecha_Cargue != value))
				{
					this.Onfecha_CargueChanging(value);
					this.SendPropertyChanging();
					this._fecha_Cargue = value;
					this.SendPropertyChanged("fecha_Cargue");
					this.Onfecha_CargueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_modificacion
		{
			get
			{
				return this._fecha_modificacion;
			}
			set
			{
				if ((this._fecha_modificacion != value))
				{
					this.Onfecha_modificacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_modificacion = value;
					this.SendPropertyChanged("fecha_modificacion");
					this.Onfecha_modificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoDocumento", DbType="Decimal(18,0) NOT NULL")]
		public decimal idTipoDocumento
		{
			get
			{
				return this._idTipoDocumento;
			}
			set
			{
				if ((this._idTipoDocumento != value))
				{
					if (this._tbl_tipoDocumento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipoDocumentoChanging(value);
					this.SendPropertyChanging();
					this._idTipoDocumento = value;
					this.SendPropertyChanged("idTipoDocumento");
					this.OnidTipoDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamanio", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string tamanio
		{
			get
			{
				return this._tamanio;
			}
			set
			{
				if ((this._tamanio != value))
				{
					this.OntamanioChanging(value);
					this.SendPropertyChanging();
					this._tamanio = value;
					this.SendPropertyChanged("tamanio");
					this.OntamanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_metadataArchivos_tblDocumentosAdjuntos", Storage="_tblDocumentosAdjuntos", ThisKey="idDMtadataArchivo", OtherKey="idDMetadaArchivo")]
		public EntitySet<tblDocumentosAdjuntos> tblDocumentosAdjuntos
		{
			get
			{
				return this._tblDocumentosAdjuntos;
			}
			set
			{
				this._tblDocumentosAdjuntos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipoDocumento_tbl_metadataArchivos", Storage="_tbl_tipoDocumento", ThisKey="idTipoDocumento", OtherKey="idTipoDocumento", IsForeignKey=true)]
		public tbl_tipoDocumento tbl_tipoDocumento
		{
			get
			{
				return this._tbl_tipoDocumento.Entity;
			}
			set
			{
				tbl_tipoDocumento previousValue = this._tbl_tipoDocumento.Entity;
				if (((previousValue != value) 
							|| (this._tbl_tipoDocumento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_tipoDocumento.Entity = null;
						previousValue.tbl_metadataArchivos.Remove(this);
					}
					this._tbl_tipoDocumento.Entity = value;
					if ((value != null))
					{
						value.tbl_metadataArchivos.Add(this);
						this._idTipoDocumento = value.idTipoDocumento;
					}
					else
					{
						this._idTipoDocumento = default(decimal);
					}
					this.SendPropertyChanged("tbl_tipoDocumento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCarpetaPersonal_tbl_metadataArchivos", Storage="_tblCarpetaPersonal", ThisKey="idCarpetaPersonal", OtherKey="idCarpetaPersonal", IsForeignKey=true)]
		public tblCarpetaPersonal tblCarpetaPersonal
		{
			get
			{
				return this._tblCarpetaPersonal.Entity;
			}
			set
			{
				tblCarpetaPersonal previousValue = this._tblCarpetaPersonal.Entity;
				if (((previousValue != value) 
							|| (this._tblCarpetaPersonal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCarpetaPersonal.Entity = null;
						previousValue.tbl_metadataArchivos.Remove(this);
					}
					this._tblCarpetaPersonal.Entity = value;
					if ((value != null))
					{
						value.tbl_metadataArchivos.Add(this);
						this._idCarpetaPersonal = value.idCarpetaPersonal;
					}
					else
					{
						this._idCarpetaPersonal = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("tblCarpetaPersonal");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDocumentosAdjuntos(tblDocumentosAdjuntos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_metadataArchivos = this;
		}
		
		private void detach_tblDocumentosAdjuntos(tblDocumentosAdjuntos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_metadataArchivos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_tipoDocumento")]
	public partial class tbl_tipoDocumento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _idTipoDocumento;
		
		private System.Nullable<int> _idTipologiaDocumental;
		
		private string _codigo;
		
		private string _tipoDocumento;
		
		private string _descripcion;
		
		private EntitySet<tbl_metadataArchivos> _tbl_metadataArchivos;
		
		private EntityRef<tbl_TipologiaDocumental> _tbl_TipologiaDocumental;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoDocumentoChanging(decimal value);
    partial void OnidTipoDocumentoChanged();
    partial void OnidTipologiaDocumentalChanging(System.Nullable<int> value);
    partial void OnidTipologiaDocumentalChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OntipoDocumentoChanging(string value);
    partial void OntipoDocumentoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public tbl_tipoDocumento()
		{
			this._tbl_metadataArchivos = new EntitySet<tbl_metadataArchivos>(new Action<tbl_metadataArchivos>(this.attach_tbl_metadataArchivos), new Action<tbl_metadataArchivos>(this.detach_tbl_metadataArchivos));
			this._tbl_TipologiaDocumental = default(EntityRef<tbl_TipologiaDocumental>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoDocumento", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal idTipoDocumento
		{
			get
			{
				return this._idTipoDocumento;
			}
			set
			{
				if ((this._idTipoDocumento != value))
				{
					this.OnidTipoDocumentoChanging(value);
					this.SendPropertyChanging();
					this._idTipoDocumento = value;
					this.SendPropertyChanged("idTipoDocumento");
					this.OnidTipoDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipologiaDocumental", DbType="Int")]
		public System.Nullable<int> idTipologiaDocumental
		{
			get
			{
				return this._idTipologiaDocumental;
			}
			set
			{
				if ((this._idTipologiaDocumental != value))
				{
					if (this._tbl_TipologiaDocumental.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipologiaDocumentalChanging(value);
					this.SendPropertyChanging();
					this._idTipologiaDocumental = value;
					this.SendPropertyChanged("idTipologiaDocumental");
					this.OnidTipologiaDocumentalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="VarChar(50)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoDocumento", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tipoDocumento
		{
			get
			{
				return this._tipoDocumento;
			}
			set
			{
				if ((this._tipoDocumento != value))
				{
					this.OntipoDocumentoChanging(value);
					this.SendPropertyChanging();
					this._tipoDocumento = value;
					this.SendPropertyChanged("tipoDocumento");
					this.OntipoDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(500)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipoDocumento_tbl_metadataArchivos", Storage="_tbl_metadataArchivos", ThisKey="idTipoDocumento", OtherKey="idTipoDocumento")]
		public EntitySet<tbl_metadataArchivos> tbl_metadataArchivos
		{
			get
			{
				return this._tbl_metadataArchivos;
			}
			set
			{
				this._tbl_metadataArchivos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_TipologiaDocumental_tbl_tipoDocumento", Storage="_tbl_TipologiaDocumental", ThisKey="idTipologiaDocumental", OtherKey="idTipologiaDocumental", IsForeignKey=true)]
		public tbl_TipologiaDocumental tbl_TipologiaDocumental
		{
			get
			{
				return this._tbl_TipologiaDocumental.Entity;
			}
			set
			{
				tbl_TipologiaDocumental previousValue = this._tbl_TipologiaDocumental.Entity;
				if (((previousValue != value) 
							|| (this._tbl_TipologiaDocumental.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_TipologiaDocumental.Entity = null;
						previousValue.tbl_tipoDocumento.Remove(this);
					}
					this._tbl_TipologiaDocumental.Entity = value;
					if ((value != null))
					{
						value.tbl_tipoDocumento.Add(this);
						this._idTipologiaDocumental = value.idTipologiaDocumental;
					}
					else
					{
						this._idTipologiaDocumental = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_TipologiaDocumental");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_metadataArchivos(tbl_metadataArchivos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipoDocumento = this;
		}
		
		private void detach_tbl_metadataArchivos(tbl_metadataArchivos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipoDocumento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_tipoId")]
	public partial class tbl_tipoId : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tipoId;
		
		private string _nombre_tipoId;
		
		private string _abreviado_tipoId;
		
		private EntitySet<tbl_usuarios> _tbl_usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipoIdChanging(int value);
    partial void Onid_tipoIdChanged();
    partial void Onnombre_tipoIdChanging(string value);
    partial void Onnombre_tipoIdChanged();
    partial void Onabreviado_tipoIdChanging(string value);
    partial void Onabreviado_tipoIdChanged();
    #endregion
		
		public tbl_tipoId()
		{
			this._tbl_usuarios = new EntitySet<tbl_usuarios>(new Action<tbl_usuarios>(this.attach_tbl_usuarios), new Action<tbl_usuarios>(this.detach_tbl_usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipoId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_tipoId
		{
			get
			{
				return this._id_tipoId;
			}
			set
			{
				if ((this._id_tipoId != value))
				{
					this.Onid_tipoIdChanging(value);
					this.SendPropertyChanging();
					this._id_tipoId = value;
					this.SendPropertyChanged("id_tipoId");
					this.Onid_tipoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_tipoId", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nombre_tipoId
		{
			get
			{
				return this._nombre_tipoId;
			}
			set
			{
				if ((this._nombre_tipoId != value))
				{
					this.Onnombre_tipoIdChanging(value);
					this.SendPropertyChanging();
					this._nombre_tipoId = value;
					this.SendPropertyChanged("nombre_tipoId");
					this.Onnombre_tipoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abreviado_tipoId", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string abreviado_tipoId
		{
			get
			{
				return this._abreviado_tipoId;
			}
			set
			{
				if ((this._abreviado_tipoId != value))
				{
					this.Onabreviado_tipoIdChanging(value);
					this.SendPropertyChanging();
					this._abreviado_tipoId = value;
					this.SendPropertyChanged("abreviado_tipoId");
					this.Onabreviado_tipoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipoId_tbl_usuarios", Storage="_tbl_usuarios", ThisKey="id_tipoId", OtherKey="tipoIdentificacion")]
		public EntitySet<tbl_usuarios> tbl_usuarios
		{
			get
			{
				return this._tbl_usuarios;
			}
			set
			{
				this._tbl_usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_usuarios(tbl_usuarios entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipoId = this;
		}
		
		private void detach_tbl_usuarios(tbl_usuarios entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipoId = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TipologiaDocumental")]
	public partial class tbl_TipologiaDocumental : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipologiaDocumental;
		
		private string _Tipologia;
		
		private EntitySet<tbl_tipoDocumento> _tbl_tipoDocumento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipologiaDocumentalChanging(int value);
    partial void OnidTipologiaDocumentalChanged();
    partial void OnTipologiaChanging(string value);
    partial void OnTipologiaChanged();
    #endregion
		
		public tbl_TipologiaDocumental()
		{
			this._tbl_tipoDocumento = new EntitySet<tbl_tipoDocumento>(new Action<tbl_tipoDocumento>(this.attach_tbl_tipoDocumento), new Action<tbl_tipoDocumento>(this.detach_tbl_tipoDocumento));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipologiaDocumental", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTipologiaDocumental
		{
			get
			{
				return this._idTipologiaDocumental;
			}
			set
			{
				if ((this._idTipologiaDocumental != value))
				{
					this.OnidTipologiaDocumentalChanging(value);
					this.SendPropertyChanging();
					this._idTipologiaDocumental = value;
					this.SendPropertyChanged("idTipologiaDocumental");
					this.OnidTipologiaDocumentalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipologia", DbType="VarChar(50)")]
		public string Tipologia
		{
			get
			{
				return this._Tipologia;
			}
			set
			{
				if ((this._Tipologia != value))
				{
					this.OnTipologiaChanging(value);
					this.SendPropertyChanging();
					this._Tipologia = value;
					this.SendPropertyChanged("Tipologia");
					this.OnTipologiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_TipologiaDocumental_tbl_tipoDocumento", Storage="_tbl_tipoDocumento", ThisKey="idTipologiaDocumental", OtherKey="idTipologiaDocumental")]
		public EntitySet<tbl_tipoDocumento> tbl_tipoDocumento
		{
			get
			{
				return this._tbl_tipoDocumento;
			}
			set
			{
				this._tbl_tipoDocumento.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_tipoDocumento(tbl_tipoDocumento entity)
		{
			this.SendPropertyChanging();
			entity.tbl_TipologiaDocumental = this;
		}
		
		private void detach_tbl_tipoDocumento(tbl_tipoDocumento entity)
		{
			this.SendPropertyChanging();
			entity.tbl_TipologiaDocumental = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuarios")]
	public partial class tbl_usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _userIdApplicacion;
		
		private string _userIdCentralizador;
		
		private string _repositorioKey;
		
		private string _carpetaUsuarioInicial;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private System.Nullable<int> _tipoIdentificacion;
		
		private string _numeroIdentificacion;
		
		private System.Nullable<bool> _Activo;
		
		private EntityRef<tbl_tipoId> _tbl_tipoId;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnuserIdApplicacionChanging(string value);
    partial void OnuserIdApplicacionChanged();
    partial void OnuserIdCentralizadorChanging(string value);
    partial void OnuserIdCentralizadorChanged();
    partial void OnrepositorioKeyChanging(string value);
    partial void OnrepositorioKeyChanged();
    partial void OncarpetaUsuarioInicialChanging(string value);
    partial void OncarpetaUsuarioInicialChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OntipoIdentificacionChanging(System.Nullable<int> value);
    partial void OntipoIdentificacionChanged();
    partial void OnnumeroIdentificacionChanging(string value);
    partial void OnnumeroIdentificacionChanged();
    partial void OnActivoChanging(System.Nullable<bool> value);
    partial void OnActivoChanged();
    #endregion
		
		public tbl_usuarios()
		{
			this._tbl_tipoId = default(EntityRef<tbl_tipoId>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userIdApplicacion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string userIdApplicacion
		{
			get
			{
				return this._userIdApplicacion;
			}
			set
			{
				if ((this._userIdApplicacion != value))
				{
					this.OnuserIdApplicacionChanging(value);
					this.SendPropertyChanging();
					this._userIdApplicacion = value;
					this.SendPropertyChanged("userIdApplicacion");
					this.OnuserIdApplicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userIdCentralizador", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string userIdCentralizador
		{
			get
			{
				return this._userIdCentralizador;
			}
			set
			{
				if ((this._userIdCentralizador != value))
				{
					this.OnuserIdCentralizadorChanging(value);
					this.SendPropertyChanging();
					this._userIdCentralizador = value;
					this.SendPropertyChanged("userIdCentralizador");
					this.OnuserIdCentralizadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repositorioKey", DbType="VarChar(50)")]
		public string repositorioKey
		{
			get
			{
				return this._repositorioKey;
			}
			set
			{
				if ((this._repositorioKey != value))
				{
					this.OnrepositorioKeyChanging(value);
					this.SendPropertyChanging();
					this._repositorioKey = value;
					this.SendPropertyChanged("repositorioKey");
					this.OnrepositorioKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carpetaUsuarioInicial", DbType="VarChar(100)")]
		public string carpetaUsuarioInicial
		{
			get
			{
				return this._carpetaUsuarioInicial;
			}
			set
			{
				if ((this._carpetaUsuarioInicial != value))
				{
					this.OncarpetaUsuarioInicialChanging(value);
					this.SendPropertyChanging();
					this._carpetaUsuarioInicial = value;
					this.SendPropertyChanged("carpetaUsuarioInicial");
					this.OncarpetaUsuarioInicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(500)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(500)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoIdentificacion", DbType="Int")]
		public System.Nullable<int> tipoIdentificacion
		{
			get
			{
				return this._tipoIdentificacion;
			}
			set
			{
				if ((this._tipoIdentificacion != value))
				{
					if (this._tbl_tipoId.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntipoIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._tipoIdentificacion = value;
					this.SendPropertyChanged("tipoIdentificacion");
					this.OntipoIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroIdentificacion", DbType="VarChar(17)")]
		public string numeroIdentificacion
		{
			get
			{
				return this._numeroIdentificacion;
			}
			set
			{
				if ((this._numeroIdentificacion != value))
				{
					this.OnnumeroIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._numeroIdentificacion = value;
					this.SendPropertyChanged("numeroIdentificacion");
					this.OnnumeroIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit")]
		public System.Nullable<bool> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipoId_tbl_usuarios", Storage="_tbl_tipoId", ThisKey="tipoIdentificacion", OtherKey="id_tipoId", IsForeignKey=true)]
		public tbl_tipoId tbl_tipoId
		{
			get
			{
				return this._tbl_tipoId.Entity;
			}
			set
			{
				tbl_tipoId previousValue = this._tbl_tipoId.Entity;
				if (((previousValue != value) 
							|| (this._tbl_tipoId.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_tipoId.Entity = null;
						previousValue.tbl_usuarios.Remove(this);
					}
					this._tbl_tipoId.Entity = value;
					if ((value != null))
					{
						value.tbl_usuarios.Add(this);
						this._tipoIdentificacion = value.id_tipoId;
					}
					else
					{
						this._tipoIdentificacion = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_tipoId");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBandejaNotificaciones")]
	public partial class tblBandejaNotificaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _idBandejaNotificaciones;
		
		private System.Nullable<decimal> _idBandejaNotificacionPadre;
		
		private string _userIdAplicacionDestino;
		
		private string _NombreEnvia;
		
		private string _userIdAplicacionOrigen;
		
		private string _Destinatarios;
		
		private System.DateTime _fechaEnvio;
		
		private string _Mensaje;
		
		private string _Asunto;
		
		private bool _Adjunto;
		
		private int _Estado;
		
		private string _tamanio;
		
		private EntitySet<tblDocumentosAdjuntos> _tblDocumentosAdjuntos;
		
		private EntityRef<tblEstadoMensajes> _tblEstadoMensajes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidBandejaNotificacionesChanging(decimal value);
    partial void OnidBandejaNotificacionesChanged();
    partial void OnidBandejaNotificacionPadreChanging(System.Nullable<decimal> value);
    partial void OnidBandejaNotificacionPadreChanged();
    partial void OnuserIdAplicacionDestinoChanging(string value);
    partial void OnuserIdAplicacionDestinoChanged();
    partial void OnNombreEnviaChanging(string value);
    partial void OnNombreEnviaChanged();
    partial void OnuserIdAplicacionOrigenChanging(string value);
    partial void OnuserIdAplicacionOrigenChanged();
    partial void OnDestinatariosChanging(string value);
    partial void OnDestinatariosChanged();
    partial void OnfechaEnvioChanging(System.DateTime value);
    partial void OnfechaEnvioChanged();
    partial void OnMensajeChanging(string value);
    partial void OnMensajeChanged();
    partial void OnAsuntoChanging(string value);
    partial void OnAsuntoChanged();
    partial void OnAdjuntoChanging(bool value);
    partial void OnAdjuntoChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OntamanioChanging(string value);
    partial void OntamanioChanged();
    #endregion
		
		public tblBandejaNotificaciones()
		{
			this._tblDocumentosAdjuntos = new EntitySet<tblDocumentosAdjuntos>(new Action<tblDocumentosAdjuntos>(this.attach_tblDocumentosAdjuntos), new Action<tblDocumentosAdjuntos>(this.detach_tblDocumentosAdjuntos));
			this._tblEstadoMensajes = default(EntityRef<tblEstadoMensajes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBandejaNotificaciones", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal idBandejaNotificaciones
		{
			get
			{
				return this._idBandejaNotificaciones;
			}
			set
			{
				if ((this._idBandejaNotificaciones != value))
				{
					this.OnidBandejaNotificacionesChanging(value);
					this.SendPropertyChanging();
					this._idBandejaNotificaciones = value;
					this.SendPropertyChanged("idBandejaNotificaciones");
					this.OnidBandejaNotificacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBandejaNotificacionPadre", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> idBandejaNotificacionPadre
		{
			get
			{
				return this._idBandejaNotificacionPadre;
			}
			set
			{
				if ((this._idBandejaNotificacionPadre != value))
				{
					this.OnidBandejaNotificacionPadreChanging(value);
					this.SendPropertyChanging();
					this._idBandejaNotificacionPadre = value;
					this.SendPropertyChanged("idBandejaNotificacionPadre");
					this.OnidBandejaNotificacionPadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userIdAplicacionDestino", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string userIdAplicacionDestino
		{
			get
			{
				return this._userIdAplicacionDestino;
			}
			set
			{
				if ((this._userIdAplicacionDestino != value))
				{
					this.OnuserIdAplicacionDestinoChanging(value);
					this.SendPropertyChanging();
					this._userIdAplicacionDestino = value;
					this.SendPropertyChanged("userIdAplicacionDestino");
					this.OnuserIdAplicacionDestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEnvia", DbType="VarChar(500)")]
		public string NombreEnvia
		{
			get
			{
				return this._NombreEnvia;
			}
			set
			{
				if ((this._NombreEnvia != value))
				{
					this.OnNombreEnviaChanging(value);
					this.SendPropertyChanging();
					this._NombreEnvia = value;
					this.SendPropertyChanged("NombreEnvia");
					this.OnNombreEnviaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userIdAplicacionOrigen", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string userIdAplicacionOrigen
		{
			get
			{
				return this._userIdAplicacionOrigen;
			}
			set
			{
				if ((this._userIdAplicacionOrigen != value))
				{
					this.OnuserIdAplicacionOrigenChanging(value);
					this.SendPropertyChanging();
					this._userIdAplicacionOrigen = value;
					this.SendPropertyChanged("userIdAplicacionOrigen");
					this.OnuserIdAplicacionOrigenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destinatarios", DbType="VarChar(MAX)")]
		public string Destinatarios
		{
			get
			{
				return this._Destinatarios;
			}
			set
			{
				if ((this._Destinatarios != value))
				{
					this.OnDestinatariosChanging(value);
					this.SendPropertyChanging();
					this._Destinatarios = value;
					this.SendPropertyChanged("Destinatarios");
					this.OnDestinatariosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaEnvio", DbType="DateTime NOT NULL")]
		public System.DateTime fechaEnvio
		{
			get
			{
				return this._fechaEnvio;
			}
			set
			{
				if ((this._fechaEnvio != value))
				{
					this.OnfechaEnvioChanging(value);
					this.SendPropertyChanging();
					this._fechaEnvio = value;
					this.SendPropertyChanged("fechaEnvio");
					this.OnfechaEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(5000) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this.OnMensajeChanging(value);
					this.SendPropertyChanging();
					this._Mensaje = value;
					this.SendPropertyChanged("Mensaje");
					this.OnMensajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asunto", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Asunto
		{
			get
			{
				return this._Asunto;
			}
			set
			{
				if ((this._Asunto != value))
				{
					this.OnAsuntoChanging(value);
					this.SendPropertyChanging();
					this._Asunto = value;
					this.SendPropertyChanged("Asunto");
					this.OnAsuntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adjunto", DbType="Bit NOT NULL")]
		public bool Adjunto
		{
			get
			{
				return this._Adjunto;
			}
			set
			{
				if ((this._Adjunto != value))
				{
					this.OnAdjuntoChanging(value);
					this.SendPropertyChanging();
					this._Adjunto = value;
					this.SendPropertyChanged("Adjunto");
					this.OnAdjuntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					if (this._tblEstadoMensajes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamanio", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string tamanio
		{
			get
			{
				return this._tamanio;
			}
			set
			{
				if ((this._tamanio != value))
				{
					this.OntamanioChanging(value);
					this.SendPropertyChanging();
					this._tamanio = value;
					this.SendPropertyChanged("tamanio");
					this.OntamanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBandejaNotificaciones_tblDocumentosAdjuntos", Storage="_tblDocumentosAdjuntos", ThisKey="idBandejaNotificaciones", OtherKey="idBandejaNotificaciones")]
		public EntitySet<tblDocumentosAdjuntos> tblDocumentosAdjuntos
		{
			get
			{
				return this._tblDocumentosAdjuntos;
			}
			set
			{
				this._tblDocumentosAdjuntos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEstadoMensajes_tblBandejaNotificaciones", Storage="_tblEstadoMensajes", ThisKey="Estado", OtherKey="idEstadoMensajes", IsForeignKey=true)]
		public tblEstadoMensajes tblEstadoMensajes
		{
			get
			{
				return this._tblEstadoMensajes.Entity;
			}
			set
			{
				tblEstadoMensajes previousValue = this._tblEstadoMensajes.Entity;
				if (((previousValue != value) 
							|| (this._tblEstadoMensajes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblEstadoMensajes.Entity = null;
						previousValue.tblBandejaNotificaciones.Remove(this);
					}
					this._tblEstadoMensajes.Entity = value;
					if ((value != null))
					{
						value.tblBandejaNotificaciones.Add(this);
						this._Estado = value.idEstadoMensajes;
					}
					else
					{
						this._Estado = default(int);
					}
					this.SendPropertyChanged("tblEstadoMensajes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDocumentosAdjuntos(tblDocumentosAdjuntos entity)
		{
			this.SendPropertyChanging();
			entity.tblBandejaNotificaciones = this;
		}
		
		private void detach_tblDocumentosAdjuntos(tblDocumentosAdjuntos entity)
		{
			this.SendPropertyChanging();
			entity.tblBandejaNotificaciones = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCarpetaPersonal")]
	public partial class tblCarpetaPersonal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _idCarpetaPersonal;
		
		private string _userIdApplicacion;
		
		private System.Nullable<decimal> _idCarpetaPadre;
		
		private string _NombreCarpeta;
		
		private EntitySet<tbl_metadataArchivos> _tbl_metadataArchivos;
		
		private EntitySet<tblCarpetaPersonal> _tblCarpetaPersonal2;
		
		private EntityRef<tblCarpetaPersonal> _tblCarpetaPersonal1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCarpetaPersonalChanging(decimal value);
    partial void OnidCarpetaPersonalChanged();
    partial void OnuserIdApplicacionChanging(string value);
    partial void OnuserIdApplicacionChanged();
    partial void OnidCarpetaPadreChanging(System.Nullable<decimal> value);
    partial void OnidCarpetaPadreChanged();
    partial void OnNombreCarpetaChanging(string value);
    partial void OnNombreCarpetaChanged();
    #endregion
		
		public tblCarpetaPersonal()
		{
			this._tbl_metadataArchivos = new EntitySet<tbl_metadataArchivos>(new Action<tbl_metadataArchivos>(this.attach_tbl_metadataArchivos), new Action<tbl_metadataArchivos>(this.detach_tbl_metadataArchivos));
			this._tblCarpetaPersonal2 = new EntitySet<tblCarpetaPersonal>(new Action<tblCarpetaPersonal>(this.attach_tblCarpetaPersonal2), new Action<tblCarpetaPersonal>(this.detach_tblCarpetaPersonal2));
			this._tblCarpetaPersonal1 = default(EntityRef<tblCarpetaPersonal>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarpetaPersonal", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal idCarpetaPersonal
		{
			get
			{
				return this._idCarpetaPersonal;
			}
			set
			{
				if ((this._idCarpetaPersonal != value))
				{
					this.OnidCarpetaPersonalChanging(value);
					this.SendPropertyChanging();
					this._idCarpetaPersonal = value;
					this.SendPropertyChanged("idCarpetaPersonal");
					this.OnidCarpetaPersonalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userIdApplicacion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string userIdApplicacion
		{
			get
			{
				return this._userIdApplicacion;
			}
			set
			{
				if ((this._userIdApplicacion != value))
				{
					this.OnuserIdApplicacionChanging(value);
					this.SendPropertyChanging();
					this._userIdApplicacion = value;
					this.SendPropertyChanged("userIdApplicacion");
					this.OnuserIdApplicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarpetaPadre", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> idCarpetaPadre
		{
			get
			{
				return this._idCarpetaPadre;
			}
			set
			{
				if ((this._idCarpetaPadre != value))
				{
					if (this._tblCarpetaPersonal1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCarpetaPadreChanging(value);
					this.SendPropertyChanging();
					this._idCarpetaPadre = value;
					this.SendPropertyChanged("idCarpetaPadre");
					this.OnidCarpetaPadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCarpeta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreCarpeta
		{
			get
			{
				return this._NombreCarpeta;
			}
			set
			{
				if ((this._NombreCarpeta != value))
				{
					this.OnNombreCarpetaChanging(value);
					this.SendPropertyChanging();
					this._NombreCarpeta = value;
					this.SendPropertyChanged("NombreCarpeta");
					this.OnNombreCarpetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCarpetaPersonal_tbl_metadataArchivos", Storage="_tbl_metadataArchivos", ThisKey="idCarpetaPersonal", OtherKey="idCarpetaPersonal")]
		public EntitySet<tbl_metadataArchivos> tbl_metadataArchivos
		{
			get
			{
				return this._tbl_metadataArchivos;
			}
			set
			{
				this._tbl_metadataArchivos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCarpetaPersonal_tblCarpetaPersonal", Storage="_tblCarpetaPersonal2", ThisKey="idCarpetaPersonal", OtherKey="idCarpetaPadre")]
		public EntitySet<tblCarpetaPersonal> tblCarpetaPersonal2
		{
			get
			{
				return this._tblCarpetaPersonal2;
			}
			set
			{
				this._tblCarpetaPersonal2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCarpetaPersonal_tblCarpetaPersonal", Storage="_tblCarpetaPersonal1", ThisKey="idCarpetaPadre", OtherKey="idCarpetaPersonal", IsForeignKey=true)]
		public tblCarpetaPersonal tblCarpetaPersonal1
		{
			get
			{
				return this._tblCarpetaPersonal1.Entity;
			}
			set
			{
				tblCarpetaPersonal previousValue = this._tblCarpetaPersonal1.Entity;
				if (((previousValue != value) 
							|| (this._tblCarpetaPersonal1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCarpetaPersonal1.Entity = null;
						previousValue.tblCarpetaPersonal2.Remove(this);
					}
					this._tblCarpetaPersonal1.Entity = value;
					if ((value != null))
					{
						value.tblCarpetaPersonal2.Add(this);
						this._idCarpetaPadre = value.idCarpetaPersonal;
					}
					else
					{
						this._idCarpetaPadre = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("tblCarpetaPersonal1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_metadataArchivos(tbl_metadataArchivos entity)
		{
			this.SendPropertyChanging();
			entity.tblCarpetaPersonal = this;
		}
		
		private void detach_tbl_metadataArchivos(tbl_metadataArchivos entity)
		{
			this.SendPropertyChanging();
			entity.tblCarpetaPersonal = null;
		}
		
		private void attach_tblCarpetaPersonal2(tblCarpetaPersonal entity)
		{
			this.SendPropertyChanging();
			entity.tblCarpetaPersonal1 = this;
		}
		
		private void detach_tblCarpetaPersonal2(tblCarpetaPersonal entity)
		{
			this.SendPropertyChanging();
			entity.tblCarpetaPersonal1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDocumentosAdjuntos")]
	public partial class tblDocumentosAdjuntos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _idDocumentosAdjuntos;
		
		private decimal _idBandejaNotificaciones;
		
		private System.Guid _idDMetadaArchivo;
		
		private EntityRef<tbl_metadataArchivos> _tbl_metadataArchivos;
		
		private EntityRef<tblBandejaNotificaciones> _tblBandejaNotificaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDocumentosAdjuntosChanging(decimal value);
    partial void OnidDocumentosAdjuntosChanged();
    partial void OnidBandejaNotificacionesChanging(decimal value);
    partial void OnidBandejaNotificacionesChanged();
    partial void OnidDMetadaArchivoChanging(System.Guid value);
    partial void OnidDMetadaArchivoChanged();
    #endregion
		
		public tblDocumentosAdjuntos()
		{
			this._tbl_metadataArchivos = default(EntityRef<tbl_metadataArchivos>);
			this._tblBandejaNotificaciones = default(EntityRef<tblBandejaNotificaciones>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDocumentosAdjuntos", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal idDocumentosAdjuntos
		{
			get
			{
				return this._idDocumentosAdjuntos;
			}
			set
			{
				if ((this._idDocumentosAdjuntos != value))
				{
					this.OnidDocumentosAdjuntosChanging(value);
					this.SendPropertyChanging();
					this._idDocumentosAdjuntos = value;
					this.SendPropertyChanged("idDocumentosAdjuntos");
					this.OnidDocumentosAdjuntosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBandejaNotificaciones", DbType="Decimal(18,0) NOT NULL")]
		public decimal idBandejaNotificaciones
		{
			get
			{
				return this._idBandejaNotificaciones;
			}
			set
			{
				if ((this._idBandejaNotificaciones != value))
				{
					if (this._tblBandejaNotificaciones.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidBandejaNotificacionesChanging(value);
					this.SendPropertyChanging();
					this._idBandejaNotificaciones = value;
					this.SendPropertyChanged("idBandejaNotificaciones");
					this.OnidBandejaNotificacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDMetadaArchivo", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid idDMetadaArchivo
		{
			get
			{
				return this._idDMetadaArchivo;
			}
			set
			{
				if ((this._idDMetadaArchivo != value))
				{
					if (this._tbl_metadataArchivos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDMetadaArchivoChanging(value);
					this.SendPropertyChanging();
					this._idDMetadaArchivo = value;
					this.SendPropertyChanged("idDMetadaArchivo");
					this.OnidDMetadaArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_metadataArchivos_tblDocumentosAdjuntos", Storage="_tbl_metadataArchivos", ThisKey="idDMetadaArchivo", OtherKey="idDMtadataArchivo", IsForeignKey=true)]
		public tbl_metadataArchivos tbl_metadataArchivos
		{
			get
			{
				return this._tbl_metadataArchivos.Entity;
			}
			set
			{
				tbl_metadataArchivos previousValue = this._tbl_metadataArchivos.Entity;
				if (((previousValue != value) 
							|| (this._tbl_metadataArchivos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_metadataArchivos.Entity = null;
						previousValue.tblDocumentosAdjuntos.Remove(this);
					}
					this._tbl_metadataArchivos.Entity = value;
					if ((value != null))
					{
						value.tblDocumentosAdjuntos.Add(this);
						this._idDMetadaArchivo = value.idDMtadataArchivo;
					}
					else
					{
						this._idDMetadaArchivo = default(System.Guid);
					}
					this.SendPropertyChanged("tbl_metadataArchivos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBandejaNotificaciones_tblDocumentosAdjuntos", Storage="_tblBandejaNotificaciones", ThisKey="idBandejaNotificaciones", OtherKey="idBandejaNotificaciones", IsForeignKey=true)]
		public tblBandejaNotificaciones tblBandejaNotificaciones
		{
			get
			{
				return this._tblBandejaNotificaciones.Entity;
			}
			set
			{
				tblBandejaNotificaciones previousValue = this._tblBandejaNotificaciones.Entity;
				if (((previousValue != value) 
							|| (this._tblBandejaNotificaciones.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblBandejaNotificaciones.Entity = null;
						previousValue.tblDocumentosAdjuntos.Remove(this);
					}
					this._tblBandejaNotificaciones.Entity = value;
					if ((value != null))
					{
						value.tblDocumentosAdjuntos.Add(this);
						this._idBandejaNotificaciones = value.idBandejaNotificaciones;
					}
					else
					{
						this._idBandejaNotificaciones = default(decimal);
					}
					this.SendPropertyChanged("tblBandejaNotificaciones");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
