#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniandes.Controlador
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OperadorCarpeta")]
	public partial class OperadorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb001_PAIS(tb001_PAIS instance);
    partial void Updatetb001_PAIS(tb001_PAIS instance);
    partial void Deletetb001_PAIS(tb001_PAIS instance);
    partial void Inserttb002_DEPARTAMENTO(tb002_DEPARTAMENTO instance);
    partial void Updatetb002_DEPARTAMENTO(tb002_DEPARTAMENTO instance);
    partial void Deletetb002_DEPARTAMENTO(tb002_DEPARTAMENTO instance);
    partial void Inserttb003_MUNICIPIO(tb003_MUNICIPIO instance);
    partial void Updatetb003_MUNICIPIO(tb003_MUNICIPIO instance);
    partial void Deletetb003_MUNICIPIO(tb003_MUNICIPIO instance);
    partial void Inserttbl_tipoId(tbl_tipoId instance);
    partial void Updatetbl_tipoId(tbl_tipoId instance);
    partial void Deletetbl_tipoId(tbl_tipoId instance);
    partial void Inserttbl_usuarios(tbl_usuarios instance);
    partial void Updatetbl_usuarios(tbl_usuarios instance);
    partial void Deletetbl_usuarios(tbl_usuarios instance);
    #endregion
		
		public OperadorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperadorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperadorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperadorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb001_PAIS> tb001_PAIS
		{
			get
			{
				return this.GetTable<tb001_PAIS>();
			}
		}
		
		public System.Data.Linq.Table<tblCarpetaPersonal> tblCarpetaPersonal
		{
			get
			{
				return this.GetTable<tblCarpetaPersonal>();
			}
		}
		
		public System.Data.Linq.Table<tb002_DEPARTAMENTO> tb002_DEPARTAMENTO
		{
			get
			{
				return this.GetTable<tb002_DEPARTAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<tb003_MUNICIPIO> tb003_MUNICIPIO
		{
			get
			{
				return this.GetTable<tb003_MUNICIPIO>();
			}
		}
		
		public System.Data.Linq.Table<tbl_tipoId> tbl_tipoId
		{
			get
			{
				return this.GetTable<tbl_tipoId>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuarios> tbl_usuarios
		{
			get
			{
				return this.GetTable<tbl_usuarios>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb001_PAIS")]
	public partial class tb001_PAIS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPais;
		
		private string _nombrePais;
		
		private string _codigoDane;
		
		private EntitySet<tb002_DEPARTAMENTO> _tb002_DEPARTAMENTO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPaisChanging(int value);
    partial void OnidPaisChanged();
    partial void OnnombrePaisChanging(string value);
    partial void OnnombrePaisChanged();
    partial void OncodigoDaneChanging(string value);
    partial void OncodigoDaneChanged();
    #endregion
		
		public tb001_PAIS()
		{
			this._tb002_DEPARTAMENTO = new EntitySet<tb002_DEPARTAMENTO>(new Action<tb002_DEPARTAMENTO>(this.attach_tb002_DEPARTAMENTO), new Action<tb002_DEPARTAMENTO>(this.detach_tb002_DEPARTAMENTO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPais", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idPais
		{
			get
			{
				return this._idPais;
			}
			set
			{
				if ((this._idPais != value))
				{
					this.OnidPaisChanging(value);
					this.SendPropertyChanging();
					this._idPais = value;
					this.SendPropertyChanged("idPais");
					this.OnidPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrePais", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombrePais
		{
			get
			{
				return this._nombrePais;
			}
			set
			{
				if ((this._nombrePais != value))
				{
					this.OnnombrePaisChanging(value);
					this.SendPropertyChanging();
					this._nombrePais = value;
					this.SendPropertyChanged("nombrePais");
					this.OnnombrePaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoDane", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigoDane
		{
			get
			{
				return this._codigoDane;
			}
			set
			{
				if ((this._codigoDane != value))
				{
					this.OncodigoDaneChanging(value);
					this.SendPropertyChanging();
					this._codigoDane = value;
					this.SendPropertyChanged("codigoDane");
					this.OncodigoDaneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb001_PAIS_tb002_DEPARTAMENTO", Storage="_tb002_DEPARTAMENTO", ThisKey="idPais", OtherKey="idPais")]
		public EntitySet<tb002_DEPARTAMENTO> tb002_DEPARTAMENTO
		{
			get
			{
				return this._tb002_DEPARTAMENTO;
			}
			set
			{
				this._tb002_DEPARTAMENTO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb002_DEPARTAMENTO(tb002_DEPARTAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.tb001_PAIS = this;
		}
		
		private void detach_tb002_DEPARTAMENTO(tb002_DEPARTAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.tb001_PAIS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCarpetaPersonal")]
	public partial class tblCarpetaPersonal
	{
		
		private decimal _idCarpetaPersonal;
		
		private string _userIdApplicacion;
		
		private System.Nullable<decimal> _idCarpetaPadre;
		
		private string _NombreCarpeta;
		
		public tblCarpetaPersonal()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarpetaPersonal", DbType="Decimal(18,0) NOT NULL")]
		public decimal idCarpetaPersonal
		{
			get
			{
				return this._idCarpetaPersonal;
			}
			set
			{
				if ((this._idCarpetaPersonal != value))
				{
					this._idCarpetaPersonal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userIdApplicacion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string userIdApplicacion
		{
			get
			{
				return this._userIdApplicacion;
			}
			set
			{
				if ((this._userIdApplicacion != value))
				{
					this._userIdApplicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarpetaPadre", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> idCarpetaPadre
		{
			get
			{
				return this._idCarpetaPadre;
			}
			set
			{
				if ((this._idCarpetaPadre != value))
				{
					this._idCarpetaPadre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCarpeta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreCarpeta
		{
			get
			{
				return this._NombreCarpeta;
			}
			set
			{
				if ((this._NombreCarpeta != value))
				{
					this._NombreCarpeta = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb002_DEPARTAMENTO")]
	public partial class tb002_DEPARTAMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDepartamento;
		
		private string _nombreDepartamento;
		
		private int _idPais;
		
		private string _codigoDANE;
		
		private EntitySet<tb003_MUNICIPIO> _tb003_MUNICIPIO;
		
		private EntityRef<tb001_PAIS> _tb001_PAIS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDepartamentoChanging(int value);
    partial void OnidDepartamentoChanged();
    partial void OnnombreDepartamentoChanging(string value);
    partial void OnnombreDepartamentoChanged();
    partial void OnidPaisChanging(int value);
    partial void OnidPaisChanged();
    partial void OncodigoDANEChanging(string value);
    partial void OncodigoDANEChanged();
    #endregion
		
		public tb002_DEPARTAMENTO()
		{
			this._tb003_MUNICIPIO = new EntitySet<tb003_MUNICIPIO>(new Action<tb003_MUNICIPIO>(this.attach_tb003_MUNICIPIO), new Action<tb003_MUNICIPIO>(this.detach_tb003_MUNICIPIO));
			this._tb001_PAIS = default(EntityRef<tb001_PAIS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					this.OnidDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._idDepartamento = value;
					this.SendPropertyChanged("idDepartamento");
					this.OnidDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreDepartamento", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombreDepartamento
		{
			get
			{
				return this._nombreDepartamento;
			}
			set
			{
				if ((this._nombreDepartamento != value))
				{
					this.OnnombreDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._nombreDepartamento = value;
					this.SendPropertyChanged("nombreDepartamento");
					this.OnnombreDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPais", DbType="Int NOT NULL")]
		public int idPais
		{
			get
			{
				return this._idPais;
			}
			set
			{
				if ((this._idPais != value))
				{
					if (this._tb001_PAIS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPaisChanging(value);
					this.SendPropertyChanging();
					this._idPais = value;
					this.SendPropertyChanged("idPais");
					this.OnidPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoDANE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigoDANE
		{
			get
			{
				return this._codigoDANE;
			}
			set
			{
				if ((this._codigoDANE != value))
				{
					this.OncodigoDANEChanging(value);
					this.SendPropertyChanging();
					this._codigoDANE = value;
					this.SendPropertyChanged("codigoDANE");
					this.OncodigoDANEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb002_DEPARTAMENTO_tb003_MUNICIPIO", Storage="_tb003_MUNICIPIO", ThisKey="idDepartamento", OtherKey="idDepartamento")]
		public EntitySet<tb003_MUNICIPIO> tb003_MUNICIPIO
		{
			get
			{
				return this._tb003_MUNICIPIO;
			}
			set
			{
				this._tb003_MUNICIPIO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb001_PAIS_tb002_DEPARTAMENTO", Storage="_tb001_PAIS", ThisKey="idPais", OtherKey="idPais", IsForeignKey=true)]
		public tb001_PAIS tb001_PAIS
		{
			get
			{
				return this._tb001_PAIS.Entity;
			}
			set
			{
				tb001_PAIS previousValue = this._tb001_PAIS.Entity;
				if (((previousValue != value) 
							|| (this._tb001_PAIS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb001_PAIS.Entity = null;
						previousValue.tb002_DEPARTAMENTO.Remove(this);
					}
					this._tb001_PAIS.Entity = value;
					if ((value != null))
					{
						value.tb002_DEPARTAMENTO.Add(this);
						this._idPais = value.idPais;
					}
					else
					{
						this._idPais = default(int);
					}
					this.SendPropertyChanged("tb001_PAIS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb003_MUNICIPIO(tb003_MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.tb002_DEPARTAMENTO = this;
		}
		
		private void detach_tb003_MUNICIPIO(tb003_MUNICIPIO entity)
		{
			this.SendPropertyChanging();
			entity.tb002_DEPARTAMENTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb003_MUNICIPIO")]
	public partial class tb003_MUNICIPIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdMunicipio;
		
		private string _nombreMunicipio;
		
		private int _idDepartamento;
		
		private string _codigoDANE;
		
		private EntityRef<tb002_DEPARTAMENTO> _tb002_DEPARTAMENTO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMunicipioChanging(int value);
    partial void OnIdMunicipioChanged();
    partial void OnnombreMunicipioChanging(string value);
    partial void OnnombreMunicipioChanged();
    partial void OnidDepartamentoChanging(int value);
    partial void OnidDepartamentoChanged();
    partial void OncodigoDANEChanging(string value);
    partial void OncodigoDANEChanged();
    #endregion
		
		public tb003_MUNICIPIO()
		{
			this._tb002_DEPARTAMENTO = default(EntityRef<tb002_DEPARTAMENTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMunicipio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdMunicipio
		{
			get
			{
				return this._IdMunicipio;
			}
			set
			{
				if ((this._IdMunicipio != value))
				{
					this.OnIdMunicipioChanging(value);
					this.SendPropertyChanging();
					this._IdMunicipio = value;
					this.SendPropertyChanged("IdMunicipio");
					this.OnIdMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreMunicipio", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombreMunicipio
		{
			get
			{
				return this._nombreMunicipio;
			}
			set
			{
				if ((this._nombreMunicipio != value))
				{
					this.OnnombreMunicipioChanging(value);
					this.SendPropertyChanging();
					this._nombreMunicipio = value;
					this.SendPropertyChanged("nombreMunicipio");
					this.OnnombreMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", DbType="Int NOT NULL")]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					if (this._tb002_DEPARTAMENTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._idDepartamento = value;
					this.SendPropertyChanged("idDepartamento");
					this.OnidDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoDANE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codigoDANE
		{
			get
			{
				return this._codigoDANE;
			}
			set
			{
				if ((this._codigoDANE != value))
				{
					this.OncodigoDANEChanging(value);
					this.SendPropertyChanging();
					this._codigoDANE = value;
					this.SendPropertyChanged("codigoDANE");
					this.OncodigoDANEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb002_DEPARTAMENTO_tb003_MUNICIPIO", Storage="_tb002_DEPARTAMENTO", ThisKey="idDepartamento", OtherKey="idDepartamento", IsForeignKey=true)]
		public tb002_DEPARTAMENTO tb002_DEPARTAMENTO
		{
			get
			{
				return this._tb002_DEPARTAMENTO.Entity;
			}
			set
			{
				tb002_DEPARTAMENTO previousValue = this._tb002_DEPARTAMENTO.Entity;
				if (((previousValue != value) 
							|| (this._tb002_DEPARTAMENTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb002_DEPARTAMENTO.Entity = null;
						previousValue.tb003_MUNICIPIO.Remove(this);
					}
					this._tb002_DEPARTAMENTO.Entity = value;
					if ((value != null))
					{
						value.tb003_MUNICIPIO.Add(this);
						this._idDepartamento = value.idDepartamento;
					}
					else
					{
						this._idDepartamento = default(int);
					}
					this.SendPropertyChanged("tb002_DEPARTAMENTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_tipoId")]
	public partial class tbl_tipoId : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tipoId;
		
		private string _nombre_tipoId;
		
		private string _abreviado_tipoId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipoIdChanging(int value);
    partial void Onid_tipoIdChanged();
    partial void Onnombre_tipoIdChanging(string value);
    partial void Onnombre_tipoIdChanged();
    partial void Onabreviado_tipoIdChanging(string value);
    partial void Onabreviado_tipoIdChanged();
    #endregion
		
		public tbl_tipoId()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipoId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_tipoId
		{
			get
			{
				return this._id_tipoId;
			}
			set
			{
				if ((this._id_tipoId != value))
				{
					this.Onid_tipoIdChanging(value);
					this.SendPropertyChanging();
					this._id_tipoId = value;
					this.SendPropertyChanged("id_tipoId");
					this.Onid_tipoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_tipoId", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nombre_tipoId
		{
			get
			{
				return this._nombre_tipoId;
			}
			set
			{
				if ((this._nombre_tipoId != value))
				{
					this.Onnombre_tipoIdChanging(value);
					this.SendPropertyChanging();
					this._nombre_tipoId = value;
					this.SendPropertyChanged("nombre_tipoId");
					this.Onnombre_tipoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abreviado_tipoId", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string abreviado_tipoId
		{
			get
			{
				return this._abreviado_tipoId;
			}
			set
			{
				if ((this._abreviado_tipoId != value))
				{
					this.Onabreviado_tipoIdChanging(value);
					this.SendPropertyChanging();
					this._abreviado_tipoId = value;
					this.SendPropertyChanged("abreviado_tipoId");
					this.Onabreviado_tipoIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuarios")]
	public partial class tbl_usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _userIdApplicacion;
		
		private string _userIdCentralizador;
		
		private string _repositorioKey;
		
		private string _carpetaUsuarioInicial;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnuserIdApplicacionChanging(string value);
    partial void OnuserIdApplicacionChanged();
    partial void OnuserIdCentralizadorChanging(string value);
    partial void OnuserIdCentralizadorChanged();
    partial void OnrepositorioKeyChanging(string value);
    partial void OnrepositorioKeyChanged();
    partial void OncarpetaUsuarioInicialChanging(string value);
    partial void OncarpetaUsuarioInicialChanged();
    #endregion
		
		public tbl_usuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userIdApplicacion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string userIdApplicacion
		{
			get
			{
				return this._userIdApplicacion;
			}
			set
			{
				if ((this._userIdApplicacion != value))
				{
					this.OnuserIdApplicacionChanging(value);
					this.SendPropertyChanging();
					this._userIdApplicacion = value;
					this.SendPropertyChanged("userIdApplicacion");
					this.OnuserIdApplicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userIdCentralizador", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string userIdCentralizador
		{
			get
			{
				return this._userIdCentralizador;
			}
			set
			{
				if ((this._userIdCentralizador != value))
				{
					this.OnuserIdCentralizadorChanging(value);
					this.SendPropertyChanging();
					this._userIdCentralizador = value;
					this.SendPropertyChanged("userIdCentralizador");
					this.OnuserIdCentralizadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repositorioKey", DbType="VarChar(50)")]
		public string repositorioKey
		{
			get
			{
				return this._repositorioKey;
			}
			set
			{
				if ((this._repositorioKey != value))
				{
					this.OnrepositorioKeyChanging(value);
					this.SendPropertyChanging();
					this._repositorioKey = value;
					this.SendPropertyChanged("repositorioKey");
					this.OnrepositorioKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carpetaUsuarioInicial", DbType="VarChar(100)")]
		public string carpetaUsuarioInicial
		{
			get
			{
				return this._carpetaUsuarioInicial;
			}
			set
			{
				if ((this._carpetaUsuarioInicial != value))
				{
					this.OncarpetaUsuarioInicialChanging(value);
					this.SendPropertyChanging();
					this._carpetaUsuarioInicial = value;
					this.SendPropertyChanged("carpetaUsuarioInicial");
					this.OncarpetaUsuarioInicialChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
